### PR TITLE
fix(daemon): add missing main_health_gate_* fields to serve.rs test helper

### LINKED ISSUE #4412: main broken: serve.rs empty_report() missing new DaemonStatusReport main_health_gate_* fields (#4404 × #4297 semantic conflict)
## Bug: main does not compile (`cargo check --workspace --all-targets`) — semantic conflict between #4404 and #4297

As of `a410a506` (feat(daemon): loom-daemon serve skeleton, PR #4404), **main is broken** for all `--all-targets` builds, which fails the `Rust Linting & Build Check` and `Rust Unit Tests` CI jobs on **every open PR**.

```
error[E0063]: missing fields `main_health_gate_deferred`, `main_health_gate_deferred_reason`
and `main_health_gate_verdict_tier` in initializer of `types::DaemonStatusReport`
   --> loom-daemon/src/serve.rs:328:9
```

## Root cause

A classic semantic merge conflict between two PRs that landed near-simultaneously (2026-07-29, ~17:00–17:20 UTC):

- `5192592e` (PR #4297, tiered build gate) added three new fields to `DaemonStatusReport` in `loom-daemon/src/types.rs`: `main_health_gate_deferred`, `main_health_gate_deferred_reason`, `main_health_gate_verdict_tier`.
- `a410a506` (PR #4404, serve skeleton) added `loom-daemon/src/serve.rs`, whose test helper `empty_report()` (line ~328) constructs a `DaemonStatusReport` literal that was written before #4297 merged and does not initialize those three fields.

Each PR was green against the main it branched from; the combination doesn't compile. The breakage is in `#[cfg(test)]` code, so `cargo build` succeeds but `cargo check --all-targets` / `cargo test` fail.

## Fix

One-line-ish: add the three missing fields (defaults: `main_health_gate_deferred: false`, `main_health_gate_deferred_reason: None`, `main_health_gate_verdict_tier: None`) to the `empty_report()` initializer in `loom-daemon/src/serve.rs`, or give `DaemonStatusReport` a `Default`/builder for test helpers so the next additive field can't break out-of-tree initializers.

## Impact

- **Severity: high** — all PR CI is red until this lands (observed failing on PR #4408's run 30475336679; PR #4407 will hit it too).
- Reproduce: `git checkout main && cargo check --workspace --all-targets`.

Discovered while evaluating PR #4408 (its diff does not touch `serve.rs`; the failure reproduces on bare main).

---

## Curator Enhancement (2026-07-29)

Verified statically against `origin/main` (`a410a506` merged): `loom-daemon/src/types.rs` defines `main_health_gate_deferred` (line ~1010), `main_health_gate_deferred_reason` (~1019), and `main_health_gate_verdict_tier` (~1027) on `DaemonStatusReport`, while `loom-daemon/src/serve.rs`'s `empty_report()` test helper (in the `#[cfg(test)]` module, initializer starting near line 328) contains zero references to any of the three — a guaranteed E0063 under `cargo check --workspace --all-targets`.

### Recommended approach

Do the minimal fix now: add the three fields to the `empty_report()` initializer with the neutral defaults the issue already states (`false` / `None` / `None`). The `Default`/builder hardening idea is a good follow-up but should NOT gate this fix — main is red and every open PR's CI is failing; land the one-liner first. If the Builder wants the hardening, file it as a separate follow-up issue rather than expanding this one.

## Acceptance Criteria

- [ ] `cargo check --workspace --all-targets` passes on the PR branch (was failing on bare main with E0063 at `serve.rs:328`)
- [ ] `cargo test -p loom-daemon serve` passes (the serve module's own tests compile and run)
- [ ] No behavior change outside `#[cfg(test)]` code — the fix touches only the test helper

## Affected Files

- `loom-daemon/src/serve.rs` — add the three missing `main_health_gate_*` fields to the `empty_report()` `DaemonStatusReport` literal (`main_health_gate_deferred: false`, `main_health_gate_deferred_reason: None`, `main_health_gate_verdict_tier: None`)
- `loom-daemon/src/types.rs` — reference only (field definitions; do not modify)

## Test Plan

- [ ] Manual verification: `cargo check --workspace --all-targets` on the branch → exits 0 (reproduce the failure first on bare main to confirm you're fixing the observed break)
- [ ] Automated tests: existing `serve.rs` tests now compile and pass via `cargo test -p loom-daemon`; no new tests required for a field-initializer fix
- [ ] Edge cases: N/A — compile-time fix in test-only code

## Related open work

- PR #4408 — where the red CI was first observed; its `Rust Linting & Build Check` failure reproduces on bare main and is not caused by that PR's diff. Landing this fix unblocks #4408 and every other open PR. Disregarded as a spec input (it's the discovery context, not a competing approach).

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

Fixes the semantic merge conflict between #4404 (serve skeleton) and #4297 (tiered build gate): `serve.rs`'s `empty_report()` test helper predates #4297's three new `DaemonStatusReport` fields, breaking `cargo check --workspace --all-targets` on main.

## Fix

Added the three missing fields to the `empty_report()` initializer with the neutral defaults the issue specifies:
- `main_health_gate_deferred: false`
- `main_health_gate_deferred_reason: None`
- `main_health_gate_verdict_tier: None`

No behavior change outside `#[cfg(test)]` code.

## Test plan

- [x] `cargo check --workspace --all-targets` passes (was failing with E0063 on bare main)
- [x] `cargo test -p loom-daemon --lib serve` — all 6 `serve::tests::*` pass, including `build_snapshot_round_trips_zero_workspaces_edge_case`

Closes #4412

### CODE REVIEW

**Comment by rjwalters** [comment]
LGTM — approving.

Verified:
- Diff is minimal (+3/-0 in `loom-daemon/src/serve.rs`), adding exactly the three neutral defaults (`main_health_gate_deferred: false`, `main_health_gate_deferred_reason: None`, `main_health_gate_verdict_tier: None`) called for in #4412's acceptance criteria — no behavior change outside `#[cfg(test)]` code.
- Programmatically confirmed no other `DaemonStatusReport` construction site is missing a field: all 36 struct fields are present in `serve.rs::empty_report`, `ipc.rs:4498`, and `main.rs:6688`.
- CI confirms the actual failure mode is fixed: "Rust Linting & Build Check" (which runs `cargo fmt --check`, `cargo clippy -D warnings`, and `cargo check --workspace --all-targets` — the exact broken command per `.github/workflows/ci.yml:58`) and "Rust Unit Tests" (`cargo test --workspace`) both pass.
- `mergeStateStatus: CLEAN`, `mergeable: MERGEABLE`.

Correct, minimal, well-targeted fix for a critical main-breaking build error.
