### ISSUE TITLE
`main` does not compile: `#4386`'s `death_class` field landed without updating the `safehouse.rs` test initializers `#4426` had just added

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/loom#4474]
## Summary

`origin/main` @ `1085e40b` fails both `Rust Unit Tests` and `Rust Linting & Build Check`. This is a **semantic merge conflict** between two PRs that were each green on their own branch — neither touched the same file, so git merged them cleanly and the breakage only appears at `cargo test` time.

```
error[E0063]: missing field `death_class` in initializer of `types::Event`
    --> loom-daemon/src/safehouse.rs:2717:21
     |
2717 |         bus.publish(Event::SweepExited {
     |                     ^^^^^^^^^^^^^^^^^^ missing `death_class`

error[E0063]: missing field `death_class` in initializer of `types::Event`
    --> loom-daemon/src/safehouse.rs:2773:21

error: could not compile `loom-daemon` (lib test) due to 2 previous errors
```

## Bisect

| Commit | Subject | Rust CI |
|---|---|---|
| `f6583a7c` | `feat(safehouse): emit completion envelopes for merged sweeps (#4426)` | **green** |
| `1085e40b` | `fix(daemon): classify claude-wrapper pre-flight deaths and trip a work…` (#4386) | **red** |

`#4426` added the two `Event::SweepExited { .. }` test initializers in `loom-daemon/src/safehouse.rs`. `#4386` added the new `death_class: Option<String>` field to the `Event::SweepExited` **and** `Event::SweepCrashed` variants (`loom-daemon/src/types.rs:1586`, `:1611`) and updated every initializer that existed *on its own branch* — but `#4386`'s branch was cut before `#4426` merged, so the two new safehouse test sites were never updated. Both PRs were green; the merge of the two is not.

## Impact

Every open PR inherits the failure, because CI builds the PR's merge with `main`. Observed on PR #4471 (issue #4415), whose own diff does not touch `safehouse.rs` at all — the red checks there are entirely inherited from `main` and should not be attributed to that PR. Expect the same on every other PR opened since `1085e40b` landed, and expect the Auditor's main-branch validation to trip.

## Fix

Two lines. Add the field to both initializers (the reaper-classification fields are `Option`, and a stub-server test has no pre-flight death to classify):

- `loom-daemon/src/safehouse.rs:2717` — add `death_class: None,` to the `Event::SweepExited { .. }` literal.
- `loom-daemon/src/safehouse.rs:2773` — same.

Verify with `cd loom-daemon && cargo test --lib safehouse` (or `cargo clippy --all-targets`, which also compiles test targets and is what caught it).

## Follow-up worth considering

`Event` is a large public-ish enum whose variants are constructed from many modules, so "add a field to a variant" is inherently a cross-file change that git cannot detect as a conflict. Two cheap mitigations, either of which would have caught this before merge:

1. A merge-queue / required "build against current `main`" check, so a PR cannot merge on a stale base. (`merge-pr.sh --auto` queues until checks pass, but the checks themselves ran against the older base.)
2. `#[non_exhaustive]`-style constructor discipline for `Event` — e.g. builder helpers or `..Default::default()` in test initializers — so additive payload extensions (which `#4386` and `#4255` both explicitly describe themselves as) stop requiring edits at every construction site.

Neither is required to close this issue; the two-line fix is.

**Comment by rjwalters** [comment]
Claimed by interactive sweep sweep-20260729T232413Z-6539-6c6e1f36 (Wave 0 — red-main emergency path: stale loom:curating reclaimed, direct to build; operator-confirmed plan).

**Comment by rjwalters** [comment]
## Already fixed on `main` — closing without a new PR

Claimed this under `loom:building` per the emergency dispatch, created worktree `.loom/worktrees/issue-4474` from `main @ fc4578a2`, and went to apply the two-line `death_class: None,` fix described above — but both sites already have it:

```
$ grep -n "Event::SweepExited {" loom-daemon/src/safehouse.rs
2754:        bus.publish(Event::SweepExited {
2811:        bus.publish(Event::SweepExited {
$ sed -n '2754,2760p;2811,2817p' loom-daemon/src/safehouse.rs
        bus.publish(Event::SweepExited {
            issue: 4426,
            exit_code: Some(0),
            duration_sec: 750,
            death_class: None,
            ...
        bus.publish(Event::SweepExited {
            issue: 4426,
            exit_code: Some(1),
            duration_sec: 90,
            death_class: None,
            ...
```

`git worktree diff` against `main` is empty — no fix is needed in the current tree.

**Bisect**: PR #4477 (`feat(daemon): opt-in idle exit for remote hosts`, merged `2026-07-29T22:49:43Z`, after this issue was filed at `22:06:19Z`) touched `loom-daemon/src/safehouse.rs` near these two test blocks and incidentally added `death_class: None,` at both of the exact line ranges this issue names (its diff hunks: `@@ -2718,6 +2755,7 @@ ... + death_class: None,` and `@@ -2774,6 +2812,7 @@ ... + death_class: None,`). So the two-line fix landed as a side effect of an unrelated PR before this issue could be picked up.

**Verified clean on `main @ fc4578a2`** (current tip):
- `cargo build -p loom-daemon` — clean
- `cargo test --lib safehouse` — 58 passed, 0 failed
- `cargo clippy --all-targets -- -D warnings` — clean
- `cargo fmt --check` — clean
- Full `cargo test` — 1970 passed, 1 failed (`disk_headroom::tests::test_worktree_root_free_gb_returns_a_value`), pre-existing and unrelated (a live free-disk-space probe, nothing to do with `Event`/`death_class`) — not touched.

Closing as completed; no code change required. No new issue filed for the flaky disk-headroom test per the "issues are suggestions" scope-discipline (out of scope here, not filing without further triage).
