### PR TITLE
fix(daemon): MCP preflight candidate fallback + role-runner missing-root hygiene

### LINKED ISSUE #4349: daemon: broken MCP worktree fails every role tick — preflight should detect/prune or skip cleanly
## Problem

A broken worktree under `.loom/worktrees/` causes **every role tick for that workspace to fail**, forever, with ERROR-level noise — the daemon neither prunes the broken worktree nor falls back to a working MCP build.

Observed 2026-07-28/29 on the loom repo itself, repeating on every 5-minute champion/curator tick:

```
[WARN] MCP entry point missing: /Users/rwalters/GitHub/loom/.loom/worktrees/issue-4188/mcp-loom/dist/index.js
[ERROR] MCP package directory not found at /Users/rwalters/GitHub/loom/.loom/worktrees/issue-4188/mcp-loom - cannot rebuild
[ERROR] MCP server pre-flight check failed
# MCP_PREFLIGHT_FAILED
[WARN] role_runner: champion tick failed ... spawn-claude.sh exited with exit status: 1
```

Net effect: the workspace's champion/curator roles are effectively disabled (every tick burns a spawn, fails in ~1.6s), and the log fills with identical ERROR blocks.

## Expected

One or more of:

1. **Preflight resolution should not pin to a broken worktree** — if the worktree's MCP build is missing and cannot be rebuilt, fall back to the primary checkout's MCP package instead of hard-failing the tick.
2. **Detect-and-prune**: a worktree with no rebuildable MCP package is dead weight; the daemon should prune it (or quarantine it out of the resolution path) and say so once.
3. **Log hygiene**: a persistent, identical failure should log on state change, not every tick (same dedup discipline the work_finder capacity advisory already uses).

## Notes

- The specific broken worktree here was `issue-4188`; the general failure mode is any stale/half-deleted worktree shadowing the MCP entry point.

---

### Verified current state — the instance has drifted clean; the structural gaps are real

The quoted failure does **not** currently reproduce on this host:

- Latest role ticks complete cleanly: `role_runner: champion tick completed for /Users/rwalters/GitHub/loom in 131.8s` (`~/.loom/daemon.log`, 2026-07-28T22:43 local); curator likewise.
- Zero `MCP_PREFLIGHT_FAILED` / "MCP package directory not found" occurrences remain in retained logs (`~/.loom/daemon.log`, `.loom/logs/role-champion.log`, `.loom/logs/role-curator.log`).
- `.loom/worktrees/` holds only `issue-4028` (open branch); `~/.loom/workspaces.json` registers only the loom + safehouse roots; the main checkout's `.mcp.json` (mtime Jun 16) points at the primary `mcp-loom/dist/index.js`, which exists and is current.

`~/.loom/daemon.log` does retain 2026-07-27 `role_runner: … tick failed … spawn-claude.sh exited with exit status: 1` entries consistent with the observation window, so the report is credible — the broken state was reaped between observation and this pass (worktree + registry cleanup; the running binary predates the #4333 registry backstop, so most likely an intervening `loom-clean`/manual cleanup — the exact reaper is unconfirmed).

**This does not close the issue.** All three requested behaviors are verifiable structural gaps in current code (below), and the failure mode recurs any time a registered workspace root goes half-broken. This is a hardening issue, not a live-incident cleanup (#4347 owns the ops-cleanup side; this issue answers its open "where was the error observed" question — the role-tick spawn path's MCP preflight).

### Root cause chain (verified against origin/main)

1. **Role ticks spawn through the wrapper's MCP preflight.** `spawn_multi_role_task` (`loom-daemon/src/role_runner.rs:671`) re-reads the workspace registry each tick and runs one invocation per registered root via `spawn-claude.sh` → `claude-wrapper.sh`; a non-zero exit is logged as a tick failure and retried next tick, forever ("never fatal" by design, module doc).
2. **Preflight pins to the workspace's own `.mcp.json` with no fallback.** `resolve_mcp_workspace()` (`defaults/scripts/claude-wrapper.sh:354`) prefers `${WORKSPACE}/.mcp.json`; `check_mcp_server()` (line ~382) extracts the entry point and, when it is missing and `_try_mcp_rebuild` (line ~535) finds no `package.json` ("cannot rebuild"), the whole session hard-fails (`MCP_PREFLIGHT_FAILED`, line ~1965). There is no fall-back to the git-common-dir (primary checkout) config, even though `mcp-loom` only ever lives in the Loom source checkout (`scripts/setup-mcp.sh:39`).
3. **How a worktree enters the chain**: any registered workspace root whose resolved `.mcp.json` points into a worktree keeps failing preflight after that worktree's `mcp-loom` build is deleted. (#4188's worktree was exactly the target-aware `setup-mcp.sh` change, merged as 9788245c / PR #4220 — an MCP-focused worktree with its own build.)
4. **The #4326 missing-root hygiene does not cover the role runner.** `work_finder` filters registry roots through `filter_missing_roots` (warn once per missing period; `work_finder.rs:1566–1612, 1771`); `spawn_multi_role_task` iterates `effective_roots()` with no such filter (`role_runner.rs:701–711`). And a *half-broken* root (dir exists, MCP build gone) passes even a missing-root filter — which is why the preflight fallback is needed in addition.
5. **No state-change dedup for tick failures**: the precedent exists in `work_finder` (`was_halted` / `was_pressured` / `was_max_concurrent`, lines ~1340–1358); the role runner logs the identical failure every tick.

### Sharpened acceptance criteria (replaces the body's "one or more of")

- [ ] **Preflight fallback**: when the resolved entry point is missing/unbuildable, `check_mcp_server` re-resolves from the git common dir's `.mcp.json` and smoke-tests that candidate before failing; the session hard-fails only when no candidate is healthy. One WARN names the broken path and the fallback used. The #4230 absent-config non-fatal skip is preserved exactly.
- [ ] **Role-runner missing-root hygiene**: `spawn_multi_role_task` applies the same missing-root discipline as `work_finder` (#4326) — a registered root that no longer exists is skipped with one warning per missing period, never spawned against.
- [ ] **Log dedup on state change**: a repeating identical role-tick failure for a workspace logs on the fail edge and on recovery, not every tick (mirror the `was_halted`/`was_pressured` discipline).
- [ ] **Scope guard — no auto-prune**: the daemon must NOT delete worktrees or run `git worktree` cleanup itself (destructive; `loom-clean` + the `.loom-managed` sentinel own that, per CLAUDE.md). The filed "detect-and-prune" option is satisfied by quarantine/skip + loud log, not deletion.

### Implementation guidance

- **Wrapper**: restructure `check_mcp_server` around an ordered candidate list — [workspace-resolved config, git-common-dir config] — taking the first whose entry point exists (after a rebuild attempt) and passes the stdio smoke test. Edit `defaults/scripts/claude-wrapper.sh` only; the installed `.loom/scripts/` copy follows via `resync-installed.sh`.
- **Rust**: consider hoisting `filter_missing_roots` (`work_finder.rs:1771`) into `workspace_registry.rs` (or a shared helper) rather than duplicating it; per-workspace failure-edge tracking is a `HashMap<PathBuf, bool>` in the tick loop, same shape as `missing_roots_warned`.

## Affected Files

- `defaults/scripts/claude-wrapper.sh` - `resolve_mcp_workspace` (~351), `check_mcp_server` (~382), `_try_mcp_rebuild` (~535), failure exit (~1965): candidate-list fallback
- `loom-daemon/src/role_runner.rs` - `spawn_multi_role_task` (~671–711): missing-root filter + per-workspace failure-edge log dedup; unit tests alongside the existing ones
- `loom-daemon/src/work_finder.rs` - share/hoist `filter_missing_roots` (~1771) if refactored (reference otherwise)
- `loom-daemon/src/workspace_registry.rs` - optional new home for the shared missing-root helper

## Test Plan

- [ ] Automated (Rust, `cargo test -p loom-daemon`): missing registered root is skipped with a single warning per missing period (edge, not per-tick); root reappears → ticks resume; a repeatedly failing tick logs once on the fail edge and once on recovery.
- [ ] Automated (shell): fixture-based test of the `check_mcp_server` fallback — workspace `.mcp.json` with a dead entry point + healthy common-dir config ⇒ preflight passes via fallback with one WARN; both candidates dead ⇒ `MCP_PREFLIGHT_FAILED`; no `.mcp.json` anywhere ⇒ #4230 skip preserved. (Source the wrapper's functions against a temp fixture tree; `tests/hooks/` shows the repo's shell-test conventions.)
- [ ] Manual verification: register a scratch worktree carrying a stale worktree-local `.mcp.json` as a workspace, delete its `mcp-loom` dir, watch one role tick → session spawns using the primary checkout's MCP with one WARN and no `MCP_PREFLIGHT_FAILED`; then delete the root entirely → skipped with one warning.
- [ ] Edge cases: unparseable `.mcp.json` (existing skip behavior preserved); `WORKSPACE` outside any git repo (no common-dir candidate → current behavior); registry load failure (existing fallback-root path unchanged).

## Related

- #4347 - the ops-cleanup twin (this issue documents the vantage its AC 1 was missing) · #4326/#4333 - missing-root registry backstop precedent · #4230 - absent-`.mcp.json` non-fatal skip (must be preserved) · #4220 - the PR whose worktree (issue-4188) exhibited the failure

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

A broken/half-deleted worktree left in the daemon's workspace registry (e.g.
`.loom/worktrees/issue-4188` after its `mcp-loom` build was removed) failed
every 5-minute champion/curator role tick forever with ERROR-level noise,
because `claude-wrapper.sh`'s MCP pre-flight pinned to that worktree's own
`.mcp.json` with no fallback, and `spawn_multi_role_task` had none of the
missing-root hygiene `work_finder` already applies.

## Changes

- `defaults/scripts/claude-wrapper.sh`: `check_mcp_server()` now iterates an
  **ordered candidate list** (`mcp_candidate_workspaces()`: the resolved
  `WORKSPACE`'s own `.mcp.json` first, then the git common dir's) instead of
  pinning to whichever `resolve_mcp_workspace()` picked. A candidate whose
  entry point is missing/unbuildable falls through to the next candidate;
  the session only hard-fails when **no** candidate config is healthy AND at
  least one candidate was a real, parseable config (the #4230 "no MCP
  configured" non-fatal skip is preserved when every candidate is absent or
  unparseable). `resolve_mcp_workspace()` is kept as a back-compat
  single-candidate wrapper over the new list.
- `loom-daemon/src/role_runner.rs`:
  - `spawn_multi_role_task` now filters registered roots through the shared
    `filter_missing_roots` (warn once per missing period, never
    auto-delete — the daemon does NOT prune worktrees itself, per CLAUDE.md;
    that stays `loom-clean`'s job).
  - Added `classify_root_tick_log` / `log_outcome_for_root_deduped`: a
    per-root failing-state map (`HashMap<PathBuf, bool>`) tracked across
    ticks so a persistently-failing root logs once on the fail edge (WARN)
    and once on recovery (INFO), with repeat failures downgraded to DEBUG —
    instead of re-warning identically every tick forever.
- `loom-daemon/src/workspace_registry.rs`: hoisted `filter_missing_roots`
  (previously private to `work_finder.rs`) here as a shared `pub fn`, along
  with its existing test suite, so `work_finder` and `role_runner` apply
  identical missing-root discipline instead of drifting copies.
- `loom-daemon/src/work_finder.rs`: now imports the hoisted
  `filter_missing_roots` instead of defining its own; behavior unchanged.
- `defaults/scripts/tests/test-mcp-config.sh`: new fixture-based section
  (real `git worktree` + stub `mcp-loom` bundles) covering the fallback,
  both-candidates-broken hard failure, and the no-config-anywhere #4230 skip.

## Acceptance Criteria Verification

| Criterion | Status | Verification |
|-----------|--------|--------------|
| Preflight fallback: broken/unbuildable entry point re-resolves from the git common dir and smoke-tests it; only fails when no candidate is healthy; one WARN names the fallback | ✅ | New `test-mcp-config.sh` Section 7 (fixture-based, real `git worktree`) — see fallback-pass, both-broken-fail, and no-config-skip cases below |
| Role-runner missing-root hygiene: `spawn_multi_role_task` applies the same discipline as `work_finder` (#4326) | ✅ | `filter_missing_roots` hoisted to `workspace_registry.rs`, applied in `spawn_multi_role_task`; new `test_multi_role_task_skips_missing_registered_root` |
| Log dedup on state change: a repeating identical role-tick failure logs on the fail edge and on recovery, not every tick | ✅ | `classify_root_tick_log` unit tests (`test_classify_first_failure_is_edge`, `test_classify_repeat_failure_is_downgraded`, `test_classify_success_after_failure_is_recovery`) + `test_log_outcome_for_root_deduped_tracks_failing_state_across_ticks` |
| Scope guard — no auto-prune: the daemon must not delete worktrees itself | ✅ | `filter_missing_roots` is warn-and-skip only (unchanged semantics from #4326); no `git worktree`/`rm` calls added anywhere in this diff |
| #4230 absent-config non-fatal skip preserved exactly | ✅ | `test-mcp-config.sh` "no .mcp.json anywhere" case asserts `RC=0` + `#4230` in the skip message |

## Test Plan

- `cargo test -p loom-daemon role_runner::` — 39 passed (includes new
  `classify_root_tick_log`/dedup tests + the missing-root multi-workspace test)
- `cargo test -p loom-daemon workspace_registry::` — 35 passed (includes the
  hoisted `filter_missing_roots` suite)
- `cargo test -p loom-daemon work_finder::` — 106 passed (unaffected by the hoist)
- `cargo test --workspace --lib --bins` — 1616 + 30 passed
- `cargo clippy -p loom-daemon --all-targets` — clean
- `cargo fmt -p loom-daemon -- --check` — clean
- `bash defaults/scripts/tests/test-mcp-config.sh` — 53 passed (7 new
  fallback/hard-fail/skip cases against a real `git worktree` fixture)
- `bash defaults/scripts/tests/test-spawn-claude.sh` — 116/129 passed;
  remaining 13 failures are pre-existing `nice`/`taskpolicy` env-specific
  failures unrelated to this change (confirmed identical failure count on
  `origin/main` before this diff)
- `bash .loom/scripts/build-gate.sh` (full repo gate: cargo test, loom-tools
  pytest, installer suite) — all green after a fresh `cargo build --release`
  (the worktree's copied release binary was stale from a prior commit,
  unrelated to this change; loom-tools `test_rust_conformance.py` was
  failing against it and now passes: 2118 passed, 1 skipped)
- Manual fixture verification (real `git init` + `git worktree add`): broken
  worktree `.mcp.json` (deleted `mcp-loom`, no `package.json` to rebuild) +
  healthy common-dir config → pre-flight passes via fallback with one WARN,
  no `MCP_PREFLIGHT_FAILED`; both broken → hard fail naming both candidates;
  no config anywhere → non-fatal `#4230` skip

Closes #4349

### CODE REVIEW

**Comment by rjwalters** [comment]
❌ **Changes Requested - Merge Conflict (complex — not a mechanical rebase)**

`mergeStateStatus` is `DIRTY`. I attempted the automated-rebase workflow in a local worktree (`.loom/worktrees/issue-4349`, nothing pushed) and want to flag why this needs Doctor rather than a quick Judge-side rebase:

**1. The textual conflict itself is simple** — both this branch and `main` (via #4364, merged after this branch diverged) independently appended new `#[test]` modules to the end of `mod tests` in `loom-daemon/src/role_runner.rs` (this PR's `classify_root_tick_log`/dedup tests vs. main's `onIdle`/`IdleTrigger`/`RoleRunGuard` tests). That part resolves cleanly by keeping both blocks.

**2. But rebasing onto current `main` does not compile** — this is the actual blocker, and it's invisible to git's line-based conflict detection (no `<<<<<<<` marker), so a naive rebase will silently ship a broken build:
- This PR deletes `fn log_outcome_for_root(role, root, outcome, elapsed)` and replaces its call site (inside `spawn_multi_role_task`) with the new `log_outcome_for_root_deduped(role, root, outcome, elapsed, failing: &mut HashMap<PathBuf, bool>)`.
- `main`'s `#4364` (idle-edge-triggered role runs, merged after this branch was cut) added a **second** call site to the plain `log_outcome_for_root` inside the new `observe_and_fire_idle` function (`loom-daemon/src/role_runner.rs:879` on current `main`).
- After rebasing, that call site still references the now-deleted `log_outcome_for_root` → `cargo build -p loom-daemon` fails with `E0425: cannot find function 'log_outcome_for_root' in this scope`.

This needs a real decision, not a mechanical merge: either (a) keep a plain (non-deduped) `log_outcome_for_root` alongside `log_outcome_for_root_deduped` for the fire-and-forget idle path (which has no per-root `failing` state to thread through), or (b) give `observe_and_fire_idle`/`IdleTrigger` access to a shared per-root failing-state map so idle-triggered runs get the same log-dedup treatment. That's a design call for Doctor/Builder, not something I should silently resolve while reviewing.

**Verified independently (worktree, not pushed anywhere):**
- `git merge-tree`/rebase confirms the textual conflict is confined to the `role_runner.rs` test module (no conflict in `claude-wrapper.sh`, `work_finder.rs`, `workspace_registry.rs`, or `test-mcp-config.sh`).
- After manually resolving the textual conflict (keeping both test blocks), `cargo build -p loom-daemon` fails with the `log_outcome_for_root` error above.
- I reset the worktree back to the original PR tip (`11ce818b`, matching `origin/feature/issue-4349` exactly) — no local or remote state was changed by this review.

**Aside on the rest of the diff (reviewed independently of the conflict):** the `claude-wrapper.sh` candidate-fallback logic (`mcp_candidate_workspaces` / `_check_mcp_candidate` / `check_mcp_server`), the `filter_missing_roots` hoist from `work_finder.rs` to `workspace_registry.rs`, and the `classify_root_tick_log`/`log_outcome_for_root_deduped` dedup logic all look sound and well-tested on their own merits — good doc comments, good return-code discipline (`set -e`-safe), and the #4230 non-fatal-skip semantics are preserved. The only blocker is the rebase-induced compile break described above.

**To fix:**
1. Rebase onto current `main`.
2. Resolve the `role_runner.rs` test-module conflict (keep both new test sections).
3. Decide how `observe_and_fire_idle`'s `log_outcome_for_root` call should interact with the new dedup logging (see options (a)/(b) above), and update that call site accordingly.
4. Re-run `cargo build -p loom-daemon`, `cargo test -p loom-daemon`, and `cargo clippy -p loom-daemon --all-targets` to confirm.

I'll re-evaluate once this is pushed.

**Comment by rjwalters** [comment]
## Rebased onto main + resolved the semantic build break

Addressed the Judge feedback (https://github.com/rjwalters/loom/pull/4376#issuecomment-5114240811). Rebased `feature/issue-4349` onto current `main` (now on top of #4375) and force-pushed.

### 1. Textual conflict (test modules)
Both this branch and #4375 (#4364) appended new `#[test]` modules to the end of `mod tests` in `loom-daemon/src/role_runner.rs`. Resolved by **keeping both** test sets — #4375's `onIdle` / `IdleTrigger` / `plan_idle_runs` / interval-guard tests **and** this PR's `classify_root_tick_log` / `log_outcome_for_root_deduped` / missing-root-hygiene tests. No test names or helpers collide.

### 2. Semantic build break — `E0425: cannot find function log_outcome_for_root`
This PR had replaced `log_outcome_for_root` with `log_outcome_for_root_deduped(..., failing: &mut HashMap<PathBuf, bool>)`, but #4375's new `observe_and_fire_idle` added a fresh call site to the old plain logger — invisible to git's line diff.

**Design decision: option (a).** I restored a plain `log_outcome_for_root` alongside the new deduped variant, and `observe_and_fire_idle` calls it. Rationale: the idle path fires **once on a busy→idle edge** as a detached `tokio::spawn` (fire-and-forget), not on a repeating tick. The per-root `failing` dedup state exists specifically to silence a *persistently-failing interval tick loop*; it has no meaning for a one-shot idle run and cannot be threaded through the detached task without inventing persistent shared state. A single plain root-aware log line is the correct, minimal fit. The restored function carries a doc comment explaining this (references #4376).

### 3. Second (hidden) semantic conflict I also fixed
#4375 added a 5th `in_progress: InProgressGuard` parameter to `spawn_multi_role_task`. This PR's new `test_multi_role_task_skips_missing_registered_root` called it with 4 args (`E0061`). Updated the test to pass `new_in_progress_guard()`.

### Verification (all in-scope checks green)
- `cargo build -p loom-daemon` — OK
- `cargo clippy -p loom-daemon --all-targets` — clean, no warnings
- `cargo fmt -p loom-daemon -- --check` — clean
- `cargo test -p loom-daemon` (lib) — **1730 passed, 0 failed**; role_runner module 60/60
- `defaults/scripts/tests/test-mcp-config.sh` — **53/53 passed** (incl. the #4349 preflight-fallback tests)

**Pre-existing failure (not from this PR):** the 9 `loom-daemon/tests/integration_basic.rs` socket tests fail with `Daemon failed to create socket within 5s`. Confirmed these fail identically on clean `main` (c4ba0cfe) — an environment/sandbox limitation, and this PR does not touch that file.

Removed `loom:merge-conflict`, back to `loom:review-requested` for re-review.

**Comment by rjwalters** [comment]
Re-review after Doctor's fixes — **approved**.

Independently verified (not just trusting the summary):

**Rebase / merge-conflict resolution**
- `git merge-base origin/main origin/feature/issue-4349` == `origin/main`'s current HEAD (`c4ba0cfe`, the #4364/#4375 idle-run commit) — the branch is a clean, fully-current rebase, not a stale merge. No leftover conflict markers in the diff.
- The `role_runner.rs` test-module conflict is resolved cleanly; `spawn_multi_role_task`'s test call site correctly passes the new 5th `in_progress: InProgressGuard` param from #4375.

**Semantic build break (the prior rejection reason)**
- `log_outcome_for_root` is restored as a plain function and is the one actually called by `observe_and_fire_idle` (confirmed by reading `origin/feature/issue-4349`'s `role_runner.rs` directly — call site at the `tokio::spawn` inside `observe_and_fire_idle`). `log_outcome_for_root_deduped` is the new variant used by the repeating interval loop in `spawn_multi_role_task`.
- The doc comment on `log_outcome_for_root` explaining *why* the idle path stays undeduped is accurate and reasonable: it's a one-shot busy→idle edge dispatched via detached `tokio::spawn`, not a repeating tick, so there's no natural per-tick `failing: &mut HashMap<PathBuf, bool>` to thread through — a plain log line is the right minimal fit there, and per-tick WARN-spam dedup (the actual #4349 problem) only matters for the repeating loop anyway.

**Build / test verification (own run, not just trusting the report)**
- `cargo build -p loom-daemon` — clean.
- `cargo test -p loom-daemon --lib role_runner::` — 60/60 passed (incl. new `classify_root_tick_log`/dedup tests and `test_multi_role_task_skips_missing_registered_root`).
- `cargo test -p loom-daemon --lib workspace_registry::` — 35/35 passed (hoisted `filter_missing_roots` suite).
- `cargo clippy -p loom-daemon --all-targets` — zero warnings.
- `cargo fmt -p loom-daemon -- --check` — clean.
- `bash defaults/scripts/tests/test-mcp-config.sh` — 53/53 passed, including the new Section 7 fallback/hard-fail/#4230-skip fixture cases.

**CI / merge state**
- `mergeStateStatus` was `UNSTABLE` at the start of this review because the "Rust Unit Tests" required check was still `IN_PROGRESS` — not a hidden failure. Polled `gh pr checks 4376` until it completed: all 7 checks now `pass`/`skipping` (MCP Server Build skips as expected — no MCP-affecting paths changed per the workflow's path filter). `gh pr view --json mergeStateStatus,mergeable` now reports `CLEAN` / `MERGEABLE`.

**Design read**
- `filter_missing_roots` hoisted from `work_finder.rs` to `workspace_registry.rs` as a shared `pub fn` — good deduplication, semantics unchanged (warn-and-skip, never auto-remove, verified by the moved test suite passing as-is).
- `classify_root_tick_log` extracted as a pure, unit-tested state-transition function — clean pattern, matches the existing `tick_is_implausibly_fast` precedent cited in the comment.
- `claude-wrapper.sh` candidate-list fallback (`mcp_candidate_workspaces`/`_check_mcp_candidate`) correctly distinguishes "not a real candidate" (rc=2, unparseable) from "real but unhealthy" (rc=1) so the #4230 non-fatal skip is preserved when every candidate is absent/unparseable, and only becomes a hard failure when at least one real candidate exists and none pass.

Pre-existing `loom-daemon/tests/integration_basic.rs` socket-creation-timeout failures are environment/sandbox related and out of scope for this PR (not touched by this diff, and CI's own "Rust Unit Tests" check — which includes that test binary — passed cleanly, consistent with those failures being local-sandbox-specific).

No blockers found. Approving.
