### PR TITLE
feat(daemon): port agent_metrics.py to native loom-daemon stats (part of #4274)

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

Completes the **metrics** slice of #4274's remaining scope (session-spawn +
metrics trio: `agent_spawn.py`, `agent_wait.py`, `agent_metrics.py`). This PR
delivers `agent_metrics.py`; the session-spawn pair
(`agent_spawn.py` + `agent_wait.py`) is deferred to follow-up issue #4415 (see
"Deviation from plan" below).

**Part of #4274** (not `Closes` — see deviation below).

## Disposition record (epic contract: port / fold / already-native-so-deleted)

| Module | Disposition | Replacement |
|---|---|---|
| `agent_metrics.py` (757 LOC) | **Ported** to native Rust | `loom-daemon stats <summary\|effectiveness\|costs\|velocity>` (`loom-daemon/src/activity/stats.rs` + `main.rs::handle_agent_metrics_command`) |
| `agent_spawn.py` (1153 LOC) | **Deferred** — follow-up issue #4415 | n/a yet |
| `agent_wait.py` (424 LOC) | **Deferred** — follow-up issue #4415 (paired with `agent_spawn.py`) | n/a yet |

## What changed

- **`loom-daemon/src/activity/stats.rs`**: new `SummaryMetrics`, `EffectivenessRow`,
  `CostRow`, `VelocityRow` types + `query_summary_metrics` / `query_effectiveness_rows`
  / `query_cost_rows` / `query_velocity_rows` — raw-SQL queries against the base
  activity tables (not the existing dashboard views, which have no period filter
  or model dimension) mirroring `agent_metrics.py`'s SQL exactly, including the
  `--by-model` (#3482) `COALESCE(NULLIF(r.model, ''), 'default')` grouping and
  `--period` (today/week/month/all) filtering. New `cargo test` coverage for all
  four.
- **`loom-daemon/src/main.rs`**: `Commands::Stats` gets a new optional positional
  `command` (`summary|effectiveness|costs|velocity`) plus `--period`/`--by-model`.
  When `command` is omitted, the **original interactive dashboard is unchanged**
  (fully backward compatible — nothing in the repo scripts `loom-daemon stats`
  without a command word besides interactive/manual use per `loom.md`). When
  `command` is given, `handle_agent_metrics_command` reproduces the Python CLI's
  behavior: role/period validation against the same allow-lists, JSON error object
  on a missing activity DB (exit 1), and text/JSON output for all four commands.
- **`defaults/scripts/agent-metrics.sh`**: repointed from
  `run_loom_tool "agent-metrics" "agent_metrics"` to `exec "$DAEMON_BIN" stats
  "$@"` (via `lib/locate-daemon-bin.sh`, the established resolution helper).
  Preserves the MCP tool's implicit-default contract: `mcp__loom__get_agent_metrics`
  only forwards an explicit command word when it isn't `"summary"`, so the script
  prepends `summary` whenever the first arg isn't one of the four command words
  (mirroring the retired Python `argparse(..., default="summary")`). The
  `--model-experiment`/`sweep-experiment` shortcut (routes to a different,
  out-of-scope Python module) is untouched.
- **`loom-tools/pyproject.toml`**: removed the `loom-agent-metrics` console
  script (commented out, matching the established pattern for prior #4274/#4272
  removals).
- **`docs/model-selection-retune.md`**: added a dated note pointing the (still
  measurement-gated, not-yet-flipped) retune procedure at the native surface —
  the CLI usage examples (`agent-metrics.sh effectiveness --by-model`, etc.) are
  unchanged for callers, only the backing implementation and its test location
  changed.
- Deleted `loom-tools/src/loom_tools/agent_metrics.py` and
  `loom-tools/tests/test_agent_metrics.py`.

## Verified at build time

- `agent_metrics.py` had zero external Python importers besides its own test
  file (confirmed against current `origin/main`).
- `agent-metrics.sh`'s other callers (`sweep.md`, `architect-patterns.md`,
  `docs/model-selection.md`, `docs/model-cost-experiment.md`) only reference the
  CLI usage (`agent-metrics.sh effectiveness --by-model`, etc.), which is
  unchanged — no further caller edits needed.
- `validate-toolchain.sh` does not reference `loom-agent-metrics` (only
  `loom-agent-wait` / `loom-agent-spawn` — those stay, since that pair is
  deferred to #4415).

## Deviation from plan: session-spawn pair deferred to #4415

The task scope asked for the full trio (`agent_spawn.py`, `agent_wait.py`,
`agent_metrics.py`) in one PR, closing #4274. After reading both files in full,
I judged that including them here was the wrong call:

- `agent_spawn.py` (1153 LOC) + `agent_wait.py` (424 LOC) manage **live**
  tmux-based Claude Code agent spawning for Manual Orchestration Mode
  (`loom start` → `agent-spawn.sh` → `agent_spawn.py`) — OAuth token injection,
  bypass-permissions-modal auto-accept, per-agent Claude-config-dir isolation,
  stuck-session detection/recovery, worktree/PYTHONPATH pinning, and log
  rotation/piping.
- They carry ~115 existing pytest cases (`test_agent_spawn.py`: 72,
  `test_agent_wait_sync.py`: 43) covering that behavior, and there is currently
  no equivalent Rust test scaffolding for tmux-session-lifecycle logic
  (`loom-daemon/src/terminal.rs`'s tests cover the daemon's own IPC-driven
  spawn path, not a standalone CLI).
- Rushing a byte-for-byte port of safety-critical live-agent-spawning logic in
  the same PR as the (much more contained, ~750 LOC) metrics port risked
  destabilizing `loom start` without adequate test coverage to catch
  regressions.

Filed **#4415** with the full technical handoff: the seams already identified
(native `loom-daemon tokens select` already replaces the Python OAuth
selector for the daemon-dispatch path — only the manual-spawn path still calls
Python; `terminal.rs`'s private `claude_config` module already mirrors
`common/claude_config.py` byte-for-byte and just needs a small CLI exposure
rather than a third reimplementation; the tmux lifecycle wrapper functions are
mechanical and may fold directly into bash per the epic's own "fold into
calling scripts" guidance), the out-of-scope `models.agent_wait` naming trap,
and acceptance criteria. `#4274` stays open with this PR as a `Part of`
increment (mirroring the precedent PR #4304 already set on this same issue for
the observability slice) rather than closing prematurely.

## Test plan

- [x] `cd loom-daemon && cargo build --bin loom-daemon` — clean
- [x] `cd loom-daemon && cargo clippy --bin loom-daemon --lib -- -D warnings` — clean
- [x] `cd loom-daemon && cargo test --lib stats` — 11 passed (7 pre-existing + 4 new)
- [x] Manual: `loom-daemon stats summary|effectiveness --by-model|costs --issue N|velocity`
      against a hand-built activity.db, both `--format json` and text — verified
      output matches Python's shape/semantics
- [x] Manual: `loom-daemon stats summary --role bogus` / `--period bogus` → exit 1
      with the expected error message
- [x] Manual: `loom-daemon stats` (no command) → unchanged original dashboard
- [x] Manual: `agent-metrics.sh` (bare, `effectiveness --by-model`, `costs --issue N --format json`, `--help`)
      via `LOOM_DAEMON_BIN` override — all forward correctly
- [x] `PYTHONPATH=loom-tools/src python3 -c "import loom_tools"` — succeeds (preserve-AC)
- [x] `cd loom-tools && python3 -m pytest -q` (excluding the pre-existing-slow
      `test_agent_spawn.py`/`test_agent_wait_sync.py`/`tests/tokens/test_agent_spawn_integration.py`/
      `test_claude_config.py`, all owned by the deferred #4415 scope, not this
      PR's diff) — 1601 passed, 35 skipped, 6 failed; **all 6 failures verified
      pre-existing on `origin/main`** via `git stash` (token-pool Rust/Python
      conformance drift in `test_rust_conformance.py` + an unrelated
      `test_logging.py` flake), unrelated to this diff

Closes: n/a (partial delivery — see Deviation section)
Part of #4274

### CODE REVIEW

**Comment by rjwalters** [comment]
## Judge review: request changes (CI blocker, not a code defect in this PR)

**Content review: solid.** I checked the diff against the `agent_metrics.py` portion of #4274's acceptance criteria:

- `loom-daemon/src/activity/stats.rs` (+473) adds `SummaryMetrics`/`EffectivenessRow`/`CostRow`/`VelocityRow` + `query_summary_metrics`/`query_effectiveness_rows`/`query_cost_rows`/`query_velocity_rows`, mirroring the deleted Python's SQL (including `--by-model` `COALESCE(NULLIF(r.model,''),'default')` and `--period` filtering) with 4 new `cargo test` cases (11/11 pass locally, see below).
- `main.rs::handle_agent_metrics_command` reproduces the Python CLI's contract closely: same command/role/period allow-list validation, same JSON error object shape (`{"error": "Activity database not available", "db_path": ...}`) on a missing activity DB with exit 1, and the pre-existing interactive `loom-daemon stats` (no subcommand) dashboard is untouched — good backward-compat call.
- `defaults/scripts/agent-metrics.sh` correctly re-implements the Python CLI's `default="summary"` argparse behavior in bash (prepends `summary` when the first arg isn't one of the four command words) so the MCP tool's implicit-default contract still holds, and correctly leaves the unrelated `--model-experiment`/`sweep-experiment` path alone.
- `loom-tools/pyproject.toml`: `loom-agent-metrics` console script commented out, matching the established removal pattern from prior #4274/#4272 PRs.
- `agent_metrics.py` + its test file deleted; no new Python added.
- Deferring `agent_spawn.py`/`agent_wait.py` to follow-up #4415 with a clear rationale (live tmux-spawn safety-criticality + no Rust test scaffolding yet) is a reasonable scope call under "Issues Are Suggestions" — `#4274` correctly stays open as a partial `Part of` increment rather than a premature `Closes`, consistent with the #4304 precedent cited in the PR body.

**But CI is red and that has to be fixed before merge.** `gh pr checks 4416` shows FAILURE on both "Rust Linting & Build Check" and "Rust Unit Tests" — both die on the same error:

```
error[E0063]: missing fields `main_health_gate_deferred`, `main_health_gate_deferred_reason`
and `main_health_gate_verdict_tier` in initializer of `types::DaemonStatusReport`
  --> loom-daemon/src/serve.rs:328:9
```

I traced this and it is **not caused by this PR's diff** — the PR never touches `serve.rs` or `types.rs`. It's a pre-existing, main-wide compile break:

- Reproduced identically on bare `origin/main` (`a7150d34`, no PR changes at all) in a scratch worktree.
- Reproduced identically on the PR's actual GitHub-computed merge commit (`04eec49e` = PR head `5bfa129d` merged into `origin/main`).
- Root cause: `serve.rs`'s `empty_report()` test helper (added by #4404, squash `a410a506`) wasn't updated for the 3 tiered-gate fields added to `DaemonStatusReport` by #4259/#4297 (`5192592e`) — a semantic conflict between two other already-merged PRs, both landed *after* this branch's fork point.
- **Already fixed** on open PR #4410 (`feature/issue-4377`, commit `ecbc4b4d` — "fix(daemon): add missing tiered-gate fields to serve.rs empty_report() helper"), which explicitly notes the break is main-wide and also hit #4407/#4411. That fix just hasn't landed on `main` yet.
- I confirmed this PR's own new code is sound in isolation: `cargo test --lib stats` in the PR worktree passes 11/11 (7 pre-existing + 4 new), and `cargo check --workspace --all-targets` succeeds cleanly on the PR branch's own tip (before merging with current main) — the failure only appears once merged with current `main`, exactly as CI computes it.

**Action needed** (either works): rebase/merge `origin/main` into this branch once #4410 lands (or independently) and re-push, or cherry-pick the 3-line `serve.rs` fix from `ecbc4b4d` directly onto this branch. Either way CI needs to go green before this can be approved — `mergeStateStatus` is currently `UNSTABLE` too.

Labeling `loom:changes-requested` + `loom:ci-failure` for the rebase; the metrics-port content itself needs no further changes from what I can see.

**Comment by rjwalters** [comment]
Doctor: CI is green — no code changes needed.

The Judge's diagnosis was correct: the failure was a **pre-existing main-wide compile break**, not a defect in this PR. `serve.rs`'s `empty_report()` test helper (added by #4404) was missing three tiered-gate fields added to `DaemonStatusReport` by #4259/#4297:

```
error[E0063]: missing fields `main_health_gate_deferred`, `main_health_gate_deferred_reason`
and `main_health_gate_verdict_tier` in initializer of `types::DaemonStatusReport`
  --> loom-daemon/src/serve.rs:328:9
```

That was already fixed on `main` by commit `ebc9b3a1` ("fix(daemon): add missing `main_health_gate_*` fields to serve.rs test helper (#4417)"). This branch simply needed to pick it up.

**What I did:** merged current `origin/main` (through `9fedc118`) into `feature/issue-4274`. Both merges were clean — no conflicts, no manual resolution. Pushed as a fast-forward: `5bfa129d..d7577eb6`.

**Scope check:** the net diff against `origin/main` is still exactly this PR's original 9 files (`+829 / -1563`) — the merges added no changes of their own.

**CI on `d7577eb6`:** all green.

| Check | Result |
|---|---|
| Rust Linting & Build Check | pass (was failing) |
| Rust Unit Tests | pass (was failing) |
| Installer Integration Tests | pass |
| Shellcheck | pass |
| CLAUDE.md Line Budget | pass |
| Detect Changes | pass |

**Local verification:** `cargo check --workspace --all-targets`, `cargo clippy --workspace --all-targets -- -D warnings`, and `cargo fmt --all --check` all clean; `cargo test --workspace` passed 1888 unit tests.

<details>
<summary>Note on a local-only integration test failure (not a PR defect)</summary>

Locally, the 9 tests in `loom-daemon/tests/integration_basic.rs` failed with `Daemon failed to create socket within 5s`. This is **environmental, not caused by this PR**:

- Running `target/debug/loom-daemon` by hand reproduces it outside the test harness entirely — the daemon initializes fine (per its own log) but never binds the socket, even after 60s.
- Several other Loom agents were concurrently running `cargo build` and `test-loom-daemon-update.sh` on this host, contending for the shared tmux/daemon surface, plus a stray `./target/debug/loom-daemon` was already running.
- These same tests pass in CI here (the "Rust Unit Tests" job runs `cargo test --workspace`), and pass on `main` (green at `9fedc118` and `e82dcbad`).

No action taken — flagging only for context. This is the known cross-agent local contention pattern, not a regression.
</details>

The metrics-port content itself was already assessed as sound in review, and is unchanged by this rebase. Handing back for re-review.

**Comment by rjwalters** [comment]
✅ **Approved!**

Full review of the `agent_metrics.py` → native `loom-daemon stats <command>` port (Part of #4274 — the non-closing reference is deliberate and correct for this epic-family partial increment, mirroring PR #4304's precedent; #4415 tracks the deferred spawn/wait pair).

## Verification performed

- **CI**: all checks green (Rust lint/build, Rust unit tests, installer integration, shellcheck, CLAUDE.md budget). Merge state CLEAN.
- **Scoped tests**: `cargo test --lib stats` in the worktree — 11 passed (7 pre-existing + 4 new parity tests).
- **SQL parity vs deleted Python** (line-by-line spot-check of `get_summary`/`get_velocity` against `origin/main`'s `agent_metrics.py`): queries match exactly, including the `COALESCE(NULLIF(r.model, ''), 'default')` model expression (#3482), the success-rate CASE, the 56-day/8-week velocity window, and `ROUND` precision. The Rust version even fixes a latent ambiguity by qualifying `i.timestamp` in the velocity query.
- **CLI-contract parity**: `--period` default `"week"`, period/role allow-lists identical to Python's `_VALID_PERIODS`/`_VALID_ROLES` (all 9 roles, incl. `shepherd`), `LOOM_ACTIVITY_DB` env override + `~/.loom/activity.db` default, and the same missing-DB error text / JSON error object with exit 1.
- **MCP contract**: verified against `mcp-loom/src/tools/terminals.ts` — `getAgentMetrics` omits the command word when it's `"summary"`, so the shim's summary-prepend in `agent-metrics.sh` is exactly the right preservation of the retired argparse default. Command-word passthrough for the other three is correct, and `--model-experiment` routing is untouched as scoped.
- **No stale references**: repo-wide grep shows no remaining importers of the deleted module (loom-api's `agent_metrics` hits are an unrelated DB table name); `pyproject.toml` console-script removal follows the established #4272/#4274 comment pattern.
- **Docs**: `model-selection-retune.md` update correctly re-anchors #3706's verification record to the native tests.

## Test Execution

**Test plan from PR description:**
1. `cargo build --bin loom-daemon` — ✅ Covered by CI (Rust Linting & Build Check green)
2. `cargo clippy -- -D warnings` — ✅ Covered by CI
3. `cargo test --lib stats` — ✅ Executed: 11 passed, 0 failed
4. Manual `loom-daemon stats <cmd>` output-shape checks — ⚠️ Not re-executed (requires hand-built activity.db); mitigated by the 4 new unit tests + SQL parity review
5. Invalid role/period → exit 1 — ✅ Verified by code inspection (allow-lists match Python exactly)
6. `loom-daemon stats` (no command) → unchanged dashboard — ✅ Verified by code inspection (`command: Option<String>`, `None` branch delegates to the untouched `handle_stats_command`)
7. `agent-metrics.sh` forwarding — ✅ Verified by inspection against the real MCP caller
8. `import loom_tools` preserve-AC — ✅ Covered by CI (Installer Integration Tests green); the 6 pre-existing pytest failures were verified by the Builder as present on origin/main

Non-blocking note: `role_sql_filter` interpolates into SQL rather than binding a parameter, but the doubled-quote escaping plus the CLI-layer allow-list makes this safe for a local CLI; matches the Python it replaces.

**Comment by rjwalters** [comment]
**Champion Auto-Merge**

This PR meets the safety criteria for automatic merging:

- Judge approved (`loom:pr` label)
- Size: 2392 lines (+829/−1563) — over the 200-line default, waived per operator policy for Judge-approved port PRs (bulk of delta is deletion of the ported `agent_metrics.py`)
- No critical files modified
- No merge conflicts (mergeable_state: clean)
- Updated recently (<1 hour ago)
- All CI checks passing

**Proceeding with squash merge...** If this was merged in error, you can revert with:
`git revert <commit-sha>`

---
*Automated by Champion role*
