### PR TITLE
fix(daemon): correct init banner's removed daemon.sh and bare role commands

### LINKED ISSUE #4379: loom-daemon init: success banner references removed daemon.sh and bare /loom
## Context
Ran `loom-daemon init <repo>` on four consumer repos (2026-07-28). The success banner ends with:

```
Daemon Mode (autonomous orchestration):
  cd <repo> && ./.loom/scripts/daemon.sh start
  Then in Claude Code: /loom
```

`./.loom/scripts/daemon.sh` was removed in #3432 (the historical shell daemon; `start-daemon.sh` survives only as a legacy wrapper mapping to the tmux agent-pool `loom` CLI, which is NOT daemon mode), and the slash command namespace is `/loom:loom`. A fresh consumer following the banner hits a missing script.

## Suggested acceptance criteria
- [ ] `loom-daemon init`'s completion text points at the current surfaces: `./.loom/scripts/cli/loom-daemon-start.sh` (or the machine-level "one daemon, many workspaces" model + `loom-daemon workspace add`, which is the actual post-#3926 story for consumer repos) and `/loom:loom`.
- [ ] No reference to removed entry points anywhere in init output (grep the init success template for `daemon.sh` / bare `/loom`).

---

### Verified enumeration (all stale-reference sites in init output)

The issue's quoted banner is confirmed on `origin/main`, plus two additional sites the original didn't list:

1. **`loom-daemon/src/main.rs:2303-2307`** — consumer init success banner (the one quoted in this issue):
   - `Then use /builder, /judge, or other role commands` — bare role commands; the installed namespace is `/loom:builder`, `/loom:judge` (files live under `.claude/commands/loom/`)
   - `cd {workspace_str} && ./.loom/scripts/daemon.sh start` — removed script (#3432)
   - `Then in Claude Code: /loom` — should be `/loom:loom`
2. **`loom-daemon/src/main.rs:2227-2229`** — the *self-install* branch banner has the same two defects: `Open Claude Code terminals with /builder, /judge, etc.` and `Or start the daemon: ./.loom/scripts/daemon.sh start`
3. **`loom-daemon/src/init/scaffolding.rs:996-997`** — stale code comment: claims `loom.sh` is "a thin wrapper around .loom/scripts/daemon.sh"; `defaults/loom.sh` actually wraps `.loom/scripts/start-daemon.sh` (the tmux agent-pool path, not daemon mode)

**Correct replacement surface, verified on `origin/main`:**
- `defaults/scripts/cli/loom-daemon-start.sh` exists and installs to `.loom/scripts/cli/loom-daemon-start.sh` in consumer repos.
- Every *other* user-facing hint in `main.rs` (10+ sites, e.g. lines 2516, 2664, 3261, 3345) already says `./.loom/scripts/cli/loom-daemon-start.sh` — the init banner block is the only holdout. Match that existing text for consistency.
- `/loom:loom` is the correct slash command (`.claude/commands/loom/loom.md` exists).
- `scripts/install-loom.sh:2109-2137` already uses the correct script path in its equivalent banner — mirror its wording, but note it too says bare `/loom` (see Out of scope).

### Recommended banner text

```text
Next steps:
  1. Commit the changes: git add -A && git commit -m 'Add Loom configuration'
  2. Choose your workflow:
     Manual Mode (recommended to start):
       cd <workspace> && claude
       Then use /loom:builder, /loom:judge, or other role commands
     Daemon Mode (autonomous orchestration):
       cd <workspace> && ./.loom/scripts/cli/loom-daemon-start.sh
       Then in Claude Code: /loom:loom
```

The machine-level "one daemon, many workspaces" model (`loom-daemon workspace add`, #3926) is the deeper story, but the per-workspace start script is what every other hint in the binary points at — keep the banner consistent with those and leave the machine-level onboarding narrative to docs.

## Acceptance Criteria

- [ ] Consumer init banner (`main.rs:2303-2307`): points at `./.loom/scripts/cli/loom-daemon-start.sh` and `/loom:loom`; role commands namespaced (`/loom:builder`, `/loom:judge`)
- [ ] Self-install banner (`main.rs:2227-2229`): same fixes
- [ ] Stale comment in `scaffolding.rs:996-997` corrected to name `start-daemon.sh`
- [ ] Guard grep passes: `grep -n 'daemon\.sh' loom-daemon/src/main.rs` returns no println/eprintln hits, and no bare `/loom`/`/builder`/`/judge` (without `loom:` prefix) remains in init output strings
- [ ] `cargo test` in `loom-daemon/` passes (the `init/mod.rs:737` test fixture writes a file *named* `daemon.sh` only to satisfy a script-count check — renaming it is optional, not required)

## Affected Files

- `loom-daemon/src/main.rs` — fix the two init banner blocks (lines 2227-2229 and 2303-2307)
- `loom-daemon/src/init/scaffolding.rs` — fix the stale wrapper comment (lines 996-997)

## Test Plan

- [ ] Manual verification: run `loom-daemon init` against a scratch repo; confirm the success banner names `./.loom/scripts/cli/loom-daemon-start.sh` and `/loom:loom`, with no `daemon.sh` / bare `/loom`
- [ ] Automated tests: `cd loom-daemon && cargo test init` passes; add or extend an assertion only if an existing test already snapshots banner text (none found — N/A otherwise)
- [ ] Edge case: self-install path (`loom-daemon init` on the Loom repo itself) shows the corrected lines from `main.rs:2227-2229`

## Out of scope

- `scripts/install-loom.sh` lines 2110/2126/2137 emit the same bare `/loom` (script path there is already correct). That file's stale info strings are tracked in #4387 — fold the bare-`/loom` fix there rather than having two PRs edit the same file.
- Broader bare-command-name sweeps in docs — tracked in #4402.

## Dependencies

None.

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

`loom-daemon init`'s success banner (both the self-install and consumer-init
branches) still pointed at the removed `.loom/scripts/daemon.sh` (deleted in
#3432) and used unnamespaced role commands. Fixes:

- Self-install banner: `/builder, /judge, etc.` -> `/loom:builder, /loom:judge, etc.`;
  `./.loom/scripts/daemon.sh start` -> `./.loom/scripts/cli/loom-daemon-start.sh`
- Consumer init banner: `/builder, /judge, or other role commands` -> `/loom:builder,
  /loom:judge, or other role commands`; `./.loom/scripts/daemon.sh start` ->
  `./.loom/scripts/cli/loom-daemon-start.sh`; `Then in Claude Code: /loom` ->
  `Then in Claude Code: /loom:loom`
- Stale comment in `scaffolding.rs` claiming `loom.sh` wraps `daemon.sh` -> corrected
  to say it wraps `.loom/scripts/start-daemon.sh` (the tmux agent-pool path)

Wording now matches the 10+ other `./.loom/scripts/cli/loom-daemon-start.sh`
sites already in `main.rs`.

Closes #4379

## Verification

- `grep -n 'daemon\.sh' loom-daemon/src/main.rs` -> no hits
- No bare `/loom`, `/builder`, `/judge` (without `loom:` prefix) remains in
  init output strings in `main.rs`
- `cargo build --bin loom-daemon` — clean
- `cargo clippy --bin loom-daemon -- -D warnings` — clean
- `cargo fmt --check` — clean

## Note: `cargo test init` blocked by a pre-existing, unrelated main breakage

`cargo test` (and therefore `cargo test init`, since the whole crate must
compile to build the test binary) currently fails to compile on unmodified
`origin/main` with:

```
error[E0063]: missing fields `main_health_gate_deferred`,
`main_health_gate_deferred_reason` and `main_health_gate_verdict_tier` in
initializer of `types::DaemonStatusReport`
  --> loom-daemon/src/serve.rs:328:9
```

This is a semantic conflict between two commits that landed minutes apart
on main (`#4297`/`5192592e` added 3 fields to `DaemonStatusReport`; `#4404`/
`a410a506` added a test-only `empty_report()` builder that predates the new
fields). I verified this reproduces identically with and without this PR's
diff (isolated via a patch file, not `git stash`, to avoid a stash race with
a concurrent builder in another worktree — see below). It is unrelated to
this issue's scope (init banner strings) and already tracked in #4412
(`loom:urgent`), so I did not fix it here per the "don't fix pre-existing
issues you notice in other files" builder policy. Once #4412 lands,
`cargo test init` should be re-run to confirm this PR's change doesn't
regress it (it touches no test code, so I don't expect any impact).

## Aside: recovered a stash race, no working-tree loss

During verification I briefly used `git stash` (before realizing it's a
repo-global shared stack across all worktrees) and popped a concurrent
builder's `feature/issue-4378` WIP into this worktree by mistake. No data
was lost: I restored their WIP as a named stash entry
(`git stash store`, message references the race + timestamp) so they can
recover it, reverted the contamination from this worktree, and reapplied my
own commit's changes via `git stash apply <commit-hash>` (found via `git
fsck --unreachable`) rather than by index. Flagging here in case the
#4378 builder notices their worktree's stash history changed.

### CODE REVIEW

**Comment by rjwalters** [comment]
Approved — clean, correctly-scoped mechanical fix.

**Diff review** (verified against `origin/main`, not a stale local checkout):
- `loom-daemon/src/main.rs`: both init banner blocks (self-install branch and consumer-init branch) now use `/loom:builder`, `/loom:judge` instead of bare `/builder`/`/judge`, and `./.loom/scripts/cli/loom-daemon-start.sh` instead of the removed `./.loom/scripts/daemon.sh`. The consumer-init "Daemon Mode" pointer now reads `/loom:loom` instead of bare `/loom`.
- `loom-daemon/src/init/scaffolding.rs`: the stale comment claiming `loom.sh` wraps `.loom/scripts/daemon.sh` now correctly says it wraps `.loom/scripts/start-daemon.sh`.
- `grep -n 'daemon\.sh' loom-daemon/src/main.rs` on the PR branch returns no hits (confirmed on the actual `pull/4413/head` ref, not a stale checkout). No bare `/loom`, `/builder`, `/judge` remain in the touched banner strings.
- Diffed the PR branch against current `origin/main`: exactly the 2 intended files changed (14 additions / 7 deletions), matching the PR description. `scripts/install-loom.sh` (#4387) is untouched, and no unrelated bare-command-name references (#4402) were touched — both correctly out of scope.

**Independently verified the CI/test-skip claim (not taken on faith):**
- Reproduced the `cargo check --workspace --all-targets` / `cargo test` failure (E0063 in `serve.rs:328`, missing `main_health_gate_*` fields on `DaemonStatusReport`) on a fresh worktree of unmodified `origin/main` — confirmed pre-existing, matches issue #4412 (`loom:urgent`) exactly.
- Reproduced the identical error, at the identical location, on the PR branch — confirms this PR's diff does not change the failure (it's not scoped anywhere near `serve.rs`/`types.rs`).
- Ran the claimed-clean commands myself on the PR branch: `cargo build --bin loom-daemon` (clean, 1m03s), `cargo clippy --bin loom-daemon -- -D warnings` (clean, no warnings), `cargo fmt --check` (clean, no output). All pass.
- Checked branch protection (`gh api repos/rjwalters/loom/rules/branches/main`): there is no `required_status_checks` rule configured, so `Rust Linting & Build Check` / `Rust Unit Tests` are non-required checks — consistent with `mergeStateStatus: UNSTABLE` rather than `BLOCKED`. Per the CI Status Check table (UNSTABLE = "Non-required checks failing → Assess if acceptable"), and given the failure is independently confirmed identical on bare main and pre-existing/tracked (#4412), I'm treating this as acceptable rather than blocking a correct, well-scoped, one-issue fix on an unrelated crate-wide compile break that isn't this PR's job to fix.
- `mergeable: MERGEABLE`.

No concerns. Approving.
