### ISSUE TITLE
claim-staleness.sh --json fails on jq 1.6: reserved $label variable

### ISSUE THREAD

**Issue by turian** [rjwalters/loom#8293]
## Observed failure

During a supervised Loom Doctor pass for 2AMLogic/gf180-torchsynth PR #100, `claim-staleness.sh check --json` failed before emitting its claim-state object. The installed script is Loom 0.19.132; the same `_emit_evaluation` code remains on upstream main `c17d63d1b40c8145ca93ead35468c1f2475a4450` in `defaults/scripts/claim-staleness.sh:338-370`.

The worker's PATH selected jq 1.6. The root independently reproduced with that exact binary. jq 1.7.1-apple and 1.8.2 accept the same filter, explaining why another worker did not encounter it.

## Minimal reproduction (no network or mutations)

With jq 1.6:

```sh
jq --version
jq -n --arg label loom:treating '{label:$label}'
```

Actual: `jq-1.6`, exit 3, and:

```text
jq: error: syntax error, unexpected label, expecting IDENT or __loc__ (Unix shell quoting issues?) at <top-level>, line 1:
{label:$label}
jq: 1 compile error
```

`label` is rejected as the jq variable identifier in this version. Renaming only the variable succeeds, preserving the public JSON key:

```sh
jq -n --arg claim_label loom:treating '{label:$claim_label}'
# {"label":"loom:treating"}
```

## End-to-end reproduction (read-only forge queries)

```sh
./.loom/scripts/claim-staleness.sh check \
  --number 100 --label loom:treating --json \
  --repo 2AMLogic/gf180-torchsynth
```

With jq 1.6 first on PATH, independently observed exit 3 and the same compilation error at `label: $label`. With jq 1.8.2, it returned valid JSON with `claim_state: fresh` for the same live claim. The `check` command performs only reads; no stand-down or claim mutation was used in this reproduction.

## Expected behavior and proposed scope

The documented JSON output should work on jq 1.6, or the helper should explicitly require a newer version before trying the filter. A narrow compatible fix is preferable: change the internal `--arg label` binding and `$label` reference to a non-keyword name while retaining the `label` output field. Claim age/activity policy need not change.

Add regression coverage for `check --json` across representative unclaimed/fresh/stale/unknown states, and the shared JSON-emission path used by `standdown`, using a jq 1.6 runner or equivalent compatibility job. A script exit must not be interpreted as an unclaimed record by callers.

## Duplicate check

Searched open and closed issues/PRs for `claim-staleness jq`, `claim-staleness 1.6`, `claim-staleness json` in titles, and `jq reserved`. No matching jq-1.6 JSON-emission report found. #6514/#6525 introduced the shared evaluator but concern claimant-activity liveness, not this filter compatibility defect. This is also separate from #8281's Bash 3.2 lease-array failure.

---

### Related Open Work

`check-duplicate.sh --issue 8293` surfaces #8281 as cross-referencing this issue. Disregarded — #8281 is a Bash 3.2 empty-array/`nounset` failure in the lease publish/renew scripts, an unrelated shell-compatibility class of bug. The issue body above already states this explicitly ("This is also separate from #8281's Bash 3.2 lease-array failure"), confirmed correct on inspection of #8281's own body (unbound `repo_args[@]`, not a jq parsing issue).

### Verified corrections

- **2026-09-19, verified against a real `jq-1.6` binary** (the `jq-linux64` asset from the `jqlang/jq` `jq-1.6` GitHub release, not jq 1.7/1.8 reasoning-by-analogy): the failure is **not** specific to the reported `{label:$label}` object-construction shape. Any **bare** `$<jq-keyword>` variable reference fails to parse on jq 1.6, regardless of surrounding syntax:
  ```
  $ ./jq16 -n --arg end "e" '$end'
  jq: error: syntax error, unexpected end, expecting IDENT or __loc__ ...
  $ ./jq16 -n --arg label "l" '$label'
  jq: error: syntax error, unexpected label, expecting IDENT or __loc__ ...
  ```
  A full sweep of jq keywords against the real jq 1.6 binary confirms all of `if then elif else end as def reduce foreach try catch import include label and or` fail as a bare `$name` reference; `not __loc__ null true false` do not.

- **2026-09-19, repo-wide verification against `origin/main`**: `git grep -noE -- '--arg(json)? +(if|then|elif|else|end|as|def|reduce|foreach|try|catch|import|include|label|and|or)\b' -- '*.sh'` (excluding `.loom/worktrees/`, which are ephemeral build state) finds **two more production call sites** beyond `claim-staleness.sh`, both independently reproduced against the real jq 1.6 binary above:
  - `defaults/scripts/check-evaluating-staleness.sh:140` — `--arg label "$LABEL"` then referenced as `.label.name==$label`. A different filter shape than the reported one (field access + comparison, not object construction) — confirmed the trigger is the bare `$label` reference itself, not adjacency to an object-construction colon.
  - `defaults/scripts/archive-transcripts.sh:275` — `--arg end "$end"`, referenced as `end_ts:(($end|select(.!="")) // null)` a few lines later (line ~286).
  - Two CI-wired test fixtures also bind `--arg end`/reference `$end` in stub filters and would themselves fail to parse under jq 1.6, independent of the feature they test: `defaults/scripts/tests/test-guide-work-log-issue-pagination.sh:161,177` and `defaults/scripts/tests/test-guide-work-log-pr-pagination.sh:172,188`.
  - No other reserved-word `--arg`/`--argjson` bindings were found in the swept file set as of this commit — re-run the grep above before relying on this being exhaustive if more time has passed.

This expands the fix scope from one file to three production scripts plus two test fixtures, all fixable with the same rename pattern the original issue already proposed.

### Acceptance Criteria

- [ ] `defaults/scripts/claim-staleness.sh` — the `_emit_evaluation()` `--arg label`/`$label` pair (originally reported, ~line 350) renamed to a non-keyword variable name; the public JSON field name `label` is unchanged.
- [ ] `defaults/scripts/check-evaluating-staleness.sh:140` — same rename applied; behavior and any consumed field/label names unchanged.
- [ ] `defaults/scripts/archive-transcripts.sh:275` — `--arg end`/`$end` renamed to a non-keyword name; the `end_ts` output field is unchanged.
- [ ] `defaults/scripts/tests/test-guide-work-log-issue-pagination.sh` and `test-guide-work-log-pr-pagination.sh` — `--arg end`/`$end` in the stub filters renamed the same way, so these suites parse under jq 1.6 too.
- [ ] A new CI-wired static check greps all `*.sh` files (excluding `.loom/worktrees/`) for `--arg(json)? <jq-keyword>` and fails the build if any match is found, using the verified reserved-word list above. This is cheap (no jq 1.6 binary needed in CI) and guards against future regressions of this exact class, not just the four call sites found today.
- [ ] `claim-staleness.sh check --json`/`standdown` output is unchanged for every documented `claim_state` (`unclaimed`, `fresh`, `stale`, `stale-bounded-fallback`, `unknown`) — extend the existing `--json` coverage (`defaults/scripts/tests/test-claim-staleness.sh:400-401`, tests T18a/T18b) rather than replacing it.
- [ ] Confirm (not new code, unless testing finds a gap) that a script exit from any of these three scripts is already treated as fail-safe/`unknown` by callers, per this repo's `judge.md`/`doctor.md`/`curator.md` "Stale claim check" convention — a compile failure must never be silently read as `unclaimed`.

### Implementation Guidance

Rename pattern for each site: keep `--arg <new_name> "$OLD_VALUE"` and update every `$<old_name>` reference in the jq filter to `$<new_name>`, while leaving the JSON **output key** (e.g. `label`, `end_ts`) exactly as it is today — those are string literals in object-construction syntax, unaffected by the internal variable rename, and downstream consumers depend on the field name, not the variable name (see `test-claim-staleness.sh:401`'s `jq -r '.label'`). Suggested names: `claim_label` for both `claim-staleness.sh` and `check-evaluating-staleness.sh` (one consistent convention across the two claim-lifecycle scripts), and `range_end` for `archive-transcripts.sh` and its two test fixtures.

For the new static check, a plain grep-based test script (no jq 1.6 binary required) is the cheapest reliable guard:

```sh
KWRE='(if|then|elif|else|end|as|def|reduce|foreach|try|catch|import|include|label|and|or)'
git grep -noE -- "--arg(json)? +${KWRE}\b" -- '*.sh' | grep -v '\.loom/worktrees/'
```

A non-empty result should fail the test. Verify no false positives against the current tree (e.g. `--arg endpoint`, `--arg label_name` must not match — confirmed safe with `\b` word-boundary in manual testing above).

### Affected Files

- `defaults/scripts/claim-staleness.sh` - rename `--arg label`/`$label` in `_emit_evaluation()` (~line 350)
- `defaults/scripts/check-evaluating-staleness.sh` - rename `--arg label`/`$label` (~line 140)
- `defaults/scripts/archive-transcripts.sh` - rename `--arg end`/`$end` (~line 275)
- `defaults/scripts/tests/test-guide-work-log-issue-pagination.sh` - rename `--arg end`/`$end` in stub filters (~lines 161, 177)
- `defaults/scripts/tests/test-guide-work-log-pr-pagination.sh` - rename `--arg end`/`$end` in stub filters (~lines 172, 188)
- `defaults/scripts/tests/test-claim-staleness.sh` - extend existing `--json` coverage across claim states under the renamed variable
- `defaults/scripts/tests/test-check-evaluating-staleness.sh` - add/extend coverage for the renamed variable
- `defaults/scripts/tests/test-archive-transcripts.sh` - add/extend coverage for the renamed variable
- `defaults/scripts/tests/test-jq-reserved-word-args.sh` (new) - static repo-wide grep guard against `--arg(json)? <jq-keyword>`
- `defaults/scripts/tests/ci-wired.txt` - register the new test script

### Test Plan

- [ ] Manual verification: run each of the three fixed scripts' affected code path locally with a real jq 1.6 binary on PATH (the `jq-linux64`/`jq-osx-amd64` asset from the `jq-1.6` GitHub release works for this) and confirm no compile error, for both the reported case and the two newly-found ones.
- [ ] Automated tests: `bash defaults/scripts/tests/test-claim-staleness.sh`, `test-check-evaluating-staleness.sh`, `test-archive-transcripts.sh`, `test-guide-work-log-issue-pagination.sh`, `test-guide-work-log-pr-pagination.sh`, and the new `test-jq-reserved-word-args.sh` all pass.
- [ ] Edge cases: confirm the new static-grep guard has no false positives against the current tree (`endpoint`, `label_name`, `reasoning`-style names must not match) and correctly fails against a deliberately reintroduced `--arg end` fixture.
