### PR TITLE
fix(daemon): downgrade dead-tmux-server restore log to debug when there is nothing to restore

### LINKED ISSUE #4378: daemon boot: restore_from_tmux logs ERROR siren twice on hosts with no tmux pool state
## Context
Every `loom-daemon` boot on a host that has never run the Manual-Orchestration-Mode tmux pool logs, at ERROR level with siren emoji:

```
[ERROR] 🚨 TMUX SERVER DEAD during restore_from_tmux - Socket should be at /private/tmp/tmux-$UID/loom
[ERROR] 🚨 TMUX SERVER DEAD during restore_from_tmux - Socket should be at /private/tmp/tmux-$UID/loom
```

(observed twice per boot, every boot, 2026-07-28/29, fresh macOS host, launchd-supervised daemon, zero tmux terminals ever created — "Restored 0 terminals"). A missing tmux server is the *expected* state on an autonomous-only host; ERROR-level siren noise trains operators to ignore the error channel, which is exactly where real failures need to land.

## Suggested acceptance criteria
- [ ] When there is no persisted terminal/pool state to restore (0 configured-or-restorable terminals), `restore_from_tmux` skips the socket probe entirely or logs at debug.
- [ ] A genuinely dead tmux server with restorable terminal state may keep the ERROR.
- [ ] No more ERROR lines on a clean autonomous-only boot.

### PR DESCRIPTION
**Pull request by rjwalters**
## Summary

`restore_from_tmux_with_filter` logs an ERROR-level 🚨 siren every time `tmux -L loom list-sessions` fails with "no server running" — even when there is nothing to restore in the first place. On a host that has never run the Manual Orchestration Mode tmux pool (e.g. autonomous-only), this fires **twice** on every daemon boot: once from the eager boot-time `restore_from_tmux()` call, and again from `list_terminals()`'s lazy re-restore (triggered because the registry is still empty after the first failed attempt). A dead server at restore time implies zero live sessions by definition, so this is the expected steady state, not an anomaly — but the ERROR-level noise trains operators to ignore the error channel, which is exactly where real failures need to land.

## Changes

- Extracted the stderr classification into a new pure helper, `TerminalManager::is_expected_empty_restore`, which recognizes the `"no server running"` condition.
- In `restore_from_tmux_with_filter`, check this classification **before** delegating to `handle_tmux_error`: if the server is dead, log at `debug` and return `Ok(())` early instead of routing through the ERROR siren. This mirrors the existing `clean_stale_sessions` precedent in the same file, which already treats the identical stderr pattern as a silent `Ok(0)`.
- `handle_tmux_error` itself is untouched — its other call sites (`new`, `has_tmux_session`, `attach_to_session`, `kill_session`) operate on sessions the daemon believes are live, where a dead server genuinely is anomalous, and its `bool` return still drives control flow there. All of its existing unit tests pass unchanged.
- Added three unit tests for the new helper: `no server running` classifies as expected-empty; `no sessions` (a distinct, already-separately-handled condition) does not; an arbitrary other tmux error does not.

## Acceptance Criteria Verification

| Criterion | Status | Verification |
|-----------|--------|--------------|
| 0 configured-or-restorable terminals: skip the socket probe entirely or log at debug | ✅ | `restore_from_tmux_with_filter` still probes (`list-sessions`), but a "no server running" failure now logs at `debug` unconditionally instead of ERROR — a dead server at restore time means zero sessions were ever restorable, so there is no distinct "configured" case to special-case (see rationale below) |
| A genuinely dead tmux server with restorable terminal state may keep the ERROR | ✅ (permissive "may", satisfied by design) | A dead server at restore time implies zero live sessions to restore *from tmux*, regardless of what a workspace config declares — retaining the ERROR via a configured-terminals heuristic would re-create the false alarm on every reboot of a normal MOM host (launchd starts the daemon before any tmux session exists). AC 2 is worded permissively, and downgrading uniformly satisfies AC 1 and AC 3 without that regression. |
| No more ERROR lines on a clean autonomous-only boot | ✅ | Both restore call sites (eager boot-time `restore_from_tmux()` and `list_terminals()`'s lazy re-restore) route through the same `is_expected_empty_restore` check, so both no longer emit ERROR when the tmux server is absent |

## Test Plan

- `cargo check` / `cargo clippy --lib -- -D warnings` — clean.
- `cargo fmt -- --check src/terminal.rs` — clean.
- `cargo test --lib terminal::` — all 52 tests in the `terminal` module pass, including the 3 new `is_expected_empty_restore` tests.
- Manual reasoning: with no `-L loom` tmux server running, `restore_from_tmux_with_filter` now hits the new early-return branch and logs at `debug` instead of calling `handle_tmux_error`, eliminating both ERROR lines per boot described in the issue.

## Pre-existing Issues (Not Addressed)

`cargo test` at the workspace level currently fails to *compile* (test-only code) due to an unrelated, already-tracked regression: #4412 (`serve.rs`'s `empty_report()` test helper is missing three `DaemonStatusReport` fields added by a near-simultaneous PR, #4297 × #4404 semantic conflict). This blocks running the full `cargo test` suite in this worktree; I verified the `terminal` module in isolation by locally reapplying #4412's documented one-line fix to `serve.rs`, running `cargo test --lib terminal::` (52/52 passed, see Test Plan), then reverting that unrelated file before committing — `src/serve.rs` has no changes in this PR's diff.

Closes #4378

### CODE REVIEW

**Comment by rjwalters** [comment]
**Approved.**

## Correctness
- `is_expected_empty_restore` is a small, pure, well-named helper. Its placement in `restore_from_tmux_with_filter` — checked *before* `handle_tmux_error` — correctly short-circuits the ERROR-level siren for the "no server running" case while leaving `handle_tmux_error`'s own call sites (`new`, `has_tmux_session`, `attach_to_session`, `kill_session`) untouched, which is the right scope: a dead server there is genuinely anomalous (the daemon believes a session is live), whereas at restore time it's the expected steady state.
- Verified against the code the PR's stated precedent: `clean_stale_sessions` (line ~1804) already treats `"no server running" || "no sessions"` as a silent `Ok(0)`, so this change brings `restore_from_tmux_with_filter` in line with existing conventions rather than inventing a new one.
- Confirmed both restore call sites (`restore_from_tmux` → `restore_from_tmux_with_filter`, and `list_terminals()`'s lazy re-restore path) route through the same check, so both ERROR lines described in #4378 are eliminated.
- The three new unit tests correctly cover the boundary: `"no server running"` → true, `"no sessions"` (a distinct, already-separately-handled condition) → false, and an arbitrary other error → false.

## Testing
- Diff is scoped entirely to `loom-daemon/src/terminal.rs` (43 lines added, 0 removed) — no `serve.rs` changes.
- Independently reproduced and confirmed the pre-existing, already-tracked #4412 compile break on bare `origin/main` (separate worktree, `cargo check --workspace --all-targets` → same `E0063` at `serve.rs:328`, missing the three `main_health_gate_*` fields from #4297 × #4404's semantic conflict). This PR's own CI failures (`Rust Linting & Build Check`, `Rust Unit Tests`) reproduce the identical `E0063` at the identical line — confirmed via the job log — so they are not caused by this PR's diff.
- To get a real (not just asserted) test signal for this PR's own code: temporarily patched the three missing fields into `serve.rs`'s `empty_report()` in the worktree (never committed, reverted immediately after), then ran `cargo test --lib terminal::` — **52/52 passed**, including all 3 new `is_expected_empty_restore` tests. `cargo fmt -- --check src/terminal.rs` is clean.

## Process notes
- `mergeStateStatus` is `UNSTABLE`/CI shows `fail` on the two Rust jobs — expected and attributable entirely to #4412 (still open, not yet fixed on main), not to this PR. Approving despite red CI here per the documented pre-existing/unrelated-and-independently-confirmed exception; this PR should auto-unblock once #4412 lands and CI is re-run/rebased.
- Issue linking: PR body ends with `Closes #4378` — correct.

Nice, tightly scoped fix with good test coverage and an honest writeup of the environmental blocker.

**Comment by rjwalters** [comment]
**Champion: Cannot Auto-Merge**

This PR cannot be automatically merged due to the following:

- **CI Status Check**: `Rust Linting & Build Check` and `Rust Unit Tests` are failing.

The failure is **inherited from broken main**, not this PR's diff: `error[E0063]: missing fields main_health_gate_deferred, main_health_gate_deferred_reason and main_health_gate_verdict_tier in initializer of types::DaemonStatusReport` — this is exactly #4412 (the #4404 × #4297 semantic conflict), which is currently `loom:building`.

**Next steps:**
- Wait for #4412's fix to merge to main
- Rebase this branch (or push a merge of main) to re-trigger CI — a green main alone will not re-run this PR's checks

Keeping `loom:pr` label. Champion will retry on the next tick once the blocking condition clears.

---
*Automated by Champion role*
