### PR TITLE
refactor(daemon): port agent_spawn.py + agent_wait.py to native loom-daemon (#4415)

### LINKED ISSUE #4415: [Parent #4274] Port agent_spawn.py + agent_wait.py to native (session-spawn pair, epic #4081 phase 3 family 4)
## Context

Epic #4081 Phase 3, family 4 remainder (marker: `loom:epic:4081:phase:3`) — this issue carries the phase marker so the Phase 4 gate ("no open issue carries `loom:epic:4081:phase:3`") stays held until the session-spawn pair is actually off Python, even after #4274 itself closes. (Marker added by Curator 2026-07-29; see comment.)

Parent: #4274 (epic #4081 Phase 3, family 4 — "port the agent/session + metrics
family to native `loom-daemon`"). #4274's scope split into two independently
deliverable slices along a real coupling seam:

1. Observability/diagnostic trio (`status`, `daemon_diagnostic`,
   `stuck_detection`, `stuck_formatting`, `health_monitor`, `forge_snapshot`,
   `models/stuck`) — delivered via PR #4304 (merged).
2. Metrics (`agent_metrics.py`) — delivered via the #4274 follow-up PR that
   files this issue (native `loom-daemon stats <command>`, `agent-metrics.sh`
   repointed, Python module + tests deleted).
3. **Session-spawn pair (`agent_spawn.py` + `agent_wait.py`) — this issue.**

The session-spawn pair is deferred separately from (2) because it is
materially larger and higher-risk: it manages **live** tmux-based Claude Code
agent spawning for Manual Orchestration Mode (`loom start` → `agent-spawn.sh`
→ `agent_spawn.py`), with ~115 existing pytest cases (`test_agent_spawn.py`:
72, `test_agent_wait_sync.py`: 43) covering OAuth-token injection,
bypass-permissions-modal auto-accept, per-agent Claude-config isolation,
stuck-session detection/recovery, worktree pinning, and log
rotation/piping — none of which currently exist as Rust tests. Rushing a
byte-for-byte port in the same PR as the metrics slice risked destabilizing
live agent spawning; this issue tracks it as its own focused unit of work.

## Scope

Port (or fold into the calling shell scripts, or delete where already-native —
verify at build time) `agent_spawn.py` (1153 LOC) and `agent_wait.py` (424
LOC), and their tests (`test_agent_spawn.py`, `test_agent_wait_sync.py`).
`agent-spawn.sh` / `agent-wait.sh` are thin stubs today (`run_loom_tool
"agent-spawn" "agent_spawn" "$@"`); their callers (`loom-start.sh`,
`agent-destroy.sh`, `guard-loom-workflow.sh`, `claude-wrapper.sh` comments)
keep their names/flags per the epic contract.

**Note:** `loom_tools.models.agent_wait` (a *different* module — dataclasses
for `WaitStatus`/`SignalType`/`CompletionReason`/`StuckConfig`, imported by
`test_validate_phase.py` and `models/__init__.py`) is NOT in scope here; do
not confuse it with the top-level `loom_tools.agent_wait` module above.

## Seams already identified (verify freshness at build time)

- **OAuth token injection is already native elsewhere.** `agent_spawn.py`'s
  `_select_oauth_token()` calls the *Python* `loom_tools.tokens.select`
  module directly. But `spawn-claude.sh` (the daemon-dispatch spawn path) and
  `claude-wrapper.sh`'s retry/capacity-recovery paths already call the native
  `loom-daemon tokens select --workspace <root> --export` (issue #4228). The
  manual-mode `agent-spawn.sh` path is the only remaining caller of the
  Python selector — replacing it with a `loom-daemon tokens select --export`
  subprocess call (mirroring `spawn-claude.sh`'s own pattern, see
  `defaults/scripts/spawn-claude.sh:357-414`) is a small, well-scoped change,
  not a new port.
- **Claude-config-dir isolation is already native, but private.**
  `loom-daemon/src/terminal.rs` has a `mod claude_config { .. }` (not `pub`)
  that already mirrors `loom_tools.common.claude_config`'s
  `setup_agent_config_dir` / `cleanup_agent_config_dir` / symlink/onboarding
  logic byte-for-byte (see the doc comment "Mirrors the Python
  implementation"), used internally by `TerminalManager::create_terminal` /
  `destroy_terminal`. There is currently no standalone CLI subcommand
  exposing it (unlike `Clean`/`RecoverOrphans`/`Tokens`, which are
  daemon-independent CLI subcommands). Exposing
  `setup_agent_config_dir`/`cleanup_agent_config_dir`/a validation check as a
  small new `loom-daemon` CLI subcommand (or reusing `create_terminal`
  itself, if a standalone tmux-session-creation CLI ends up being the shape
  of the port) removes the need to re-implement config-dir isolation a third
  time (it already exists in Python + Rust).
- **tmux session lifecycle (`_tmux()` wrapper, `session_exists`,
  `session_is_alive`, `kill_stuck_session`, `capture_tmux_output`,
  `list_sessions`) is mechanical subprocess-wrapping** — `terminal.rs`'s
  `TerminalManager` already owns equivalent lifecycle methods
  (`create_terminal`, `destroy_terminal`, `has_tmux_session`, `kill_session`,
  `restore_from_tmux`) but only via the running daemon's IPC surface, not a
  standalone CLI. Decide at build time whether a new standalone
  `loom-daemon` subcommand (same "no running daemon required" shape as
  `Clean`/`RecoverOrphans`) or folding the tmux calls directly into
  `agent-spawn.sh`/`agent-wait.sh` as bash is the better fit — the curator
  note on #4274 explicitly permits folding trivial parts into the calling
  shell scripts instead of a full Rust port.
- **Bypass-permissions-modal auto-accept, stuck-session
  detection/log-rotation, worktree/PYTHONPATH pinning, and the
  `check_log_for_api_errors` heuristics** have no existing native equivalent
  and are the actual net-new logic to port (or reimplement in bash).

## Out of scope

- `models/spawn_loop_state.py` / `common/state.py::read_spawn_loop_state()` —
  owned by #4272 (family 2), not this family.
- `loom_tools.models.agent_wait` (see Note above).
- The metrics slice (`agent_metrics.py`) — delivered via #4274's own PR.

## Acceptance criteria

- [ ] `agent_spawn.py` and `agent_wait.py` have no remaining external Python
      callers (verify at build time — confirmed zero as of 2026-07-29 besides
      their own tests).
- [ ] `agent-spawn.sh` / `agent-wait.sh` keep their CLI contract (flags,
      exit codes, `--json` output shape) for `loom-start.sh` and
      `agent-destroy.sh`.
- [ ] OAuth token injection for the manual-spawn path uses
      `loom-daemon tokens select --export` (native), not
      `loom_tools.tokens.select`.
- [ ] Claude-config-dir isolation reuses the existing `terminal.rs`
      `claude_config` module (exposed via a small CLI addition) rather than
      a third reimplementation.
- [ ] Equivalent test coverage exists for the ported/rewritten logic (Rust
      `cargo test` and/or bats-style bash tests) — do not ship the port with
      materially less coverage than the ~115 existing pytest cases.
- [ ] `loom-tools/pyproject.toml`'s `loom-agent-wait` / `loom-agent-spawn`
      console scripts removed once the Python modules are deleted.
- [ ] Manual smoke test: `loom start` spawns a role successfully in a
      zero-pip consumer workspace (this is the live path being changed).

## Estimated effort

Complex (roughly 6-10+ hours): >8 files, >400 LOC, multiple genuinely
distinct concerns (tmux lifecycle, OAuth injection, config isolation, stuck
detection, log piping) each needing its own decision (port to Rust / fold
into bash / already-native-delete). Decompose further at build time if any
sub-concern proves independently large (e.g. stuck-session
detection/recovery could split from the core spawn+wait pair).

---

## Curator Enhancement (2026-07-29)

Verified against `origin/main` @ `abf47697`. Confirmed accurate: `terminal.rs` private `mod claude_config` (line 15) with `setup_agent_config_dir`/`cleanup_agent_config_dir`; `spawn-claude.sh`'s native `tokens select --workspace … --export` pattern; `pyproject.toml` console scripts `loom-agent-wait` (line 19) / `loom-agent-spawn` (line 50); the `loom_tools.models.agent_wait` disambiguation note.

### Corrections to the original enumeration

1. **AC "no remaining external Python callers … confirmed zero besides their own tests" is stale/incomplete.** Two additional test files import the modules under deletion and must be ported or deleted with them:
   - `loom-tools/tests/test_api_error_detection.py` — imports `API_ERROR_PATTERNS`, `check_log_for_api_errors` from `loom_tools.agent_spawn`.
   - `loom-tools/tests/tokens/test_agent_spawn_integration.py` — OAuth-token-injection integration tests for `agent_spawn` (also imports `common.claude_config`). Note `defaults/scripts/build-gate.sh:123` carries an `--ignore=tests/tokens/test_agent_spawn_integration.py` line that must be dropped when the file is deleted.
2. **`defaults/scripts/validate-toolchain.sh` hard-requires the console scripts being removed** (`loom-agent-wait`/`loom-agent-spawn` in its required-tools array, lines 40–41, and help text, lines 71–72). Removing them from `pyproject.toml` without updating this script breaks toolchain validation. (Check how PR #4416 handled `loom-agent-metrics` here and mirror it.)
3. **Two shared `common/` modules become orphans after the port** — decide delete-vs-keep at build time (deletion is consistent with the epic's Python-removal goal):
   - `common/tmux_session.py` — only consumers are `agent_spawn.py`, `agent_wait.py`, the `common/__init__.py` re-export, and its own `test_tmux_session.py`.
   - `common/claude_config.py` — only consumers are `agent_spawn.py`, `test_claude_config.py`, and `tokens/test_agent_spawn_integration.py`; `terminal.rs`'s `claude_config` module is the byte-for-byte Rust mirror and becomes the sole implementation. If deleted, delete `test_claude_config.py` / `test_tmux_session.py` with them and clean the `common/__init__.py` re-exports.
4. Minor LOC drift: `agent_spawn.py` is 1165 lines on current main (body says 1153).

### Dependencies

- [x] #4416: metrics-slice PR (part of #4274) — **merged 2026-07-29 19:18 UTC**; `agent_metrics.py` verified gone from `origin/main` @ `5f11d433`.

Dependency complete — `loom:blocked` removed 2026-07-29; anchors re-verified against the post-#4416 build base (see Re-verification below).

### Re-verification (2026-07-29, post-#4416, origin/main @ `5f11d433`)

- All paths in Affected Files confirmed present on `origin/main` (curator pre-flight, exact-match).
- `pyproject.toml`: `loom-agent-wait` still line 19; `loom-agent-spawn` drifted to **line 54**. #4416's pattern for removing `loom-agent-metrics` was a **comment-out with an explanatory comment block** (lines 48–52), not silent deletion — mirror that pattern per Correction 2.
- `validate-toolchain.sh`: besides the required-tools array (lines 40–41) and help text (71–72), the console-script → module `case` mapping at **lines 144–145** also carries `loom-agent-wait`/`loom-agent-spawn` entries to drop. (#4416 removed all agent-metrics references from this file — zero remain.)
- `build-gate.sh:123` `--ignore=tests/tokens/test_agent_spawn_integration.py` still present; `terminal.rs:15` `mod claude_config {` unchanged.

### Affected Files

- `loom-tools/src/loom_tools/agent_spawn.py` — delete (port/fold logic per the seams above)
- `loom-tools/src/loom_tools/agent_wait.py` — delete (same)
- `loom-tools/tests/test_agent_spawn.py`, `loom-tools/tests/test_agent_wait_sync.py` — delete; coverage moves to Rust/bats
- `loom-tools/tests/test_api_error_detection.py` — delete/port (imports from `agent_spawn`)
- `loom-tools/tests/tokens/test_agent_spawn_integration.py` — delete/port (token-injection behavior moves to the native `tokens select` path)
- `loom-tools/src/loom_tools/common/tmux_session.py`, `common/claude_config.py`, `common/__init__.py` (+ `tests/test_tmux_session.py`, `tests/test_claude_config.py`) — orphan cleanup per Correction 3
- `loom-tools/pyproject.toml` — remove `loom-agent-wait` / `loom-agent-spawn` console scripts
- `defaults/scripts/agent-spawn.sh`, `defaults/scripts/agent-wait.sh` — repoint stubs from `run_loom_tool` to the native implementation, preserving flags/exit codes/`--json` shape
- `defaults/scripts/validate-toolchain.sh` — drop the removed console scripts from the required-tools list and help text
- `defaults/scripts/build-gate.sh` — drop the `--ignore=tests/tokens/test_agent_spawn_integration.py` line (123)
- `loom-daemon/src/terminal.rs` — expose `claude_config` (small CLI surface) per AC; reference for tmux lifecycle
- `loom-daemon/src/main.rs` — new daemon-independent CLI subcommand(s), same shape as `Clean`/`RecoverOrphans`/`Tokens`
- `defaults/scripts/spawn-claude.sh` — reference only (`tokens select --export` pattern, ~lines 357–414)

### Test Plan

- [ ] Automated (Rust/bats): equivalent coverage for the ~115 pytest cases in `test_agent_spawn.py` (72) + `test_agent_wait_sync.py` (43), **plus** `test_api_error_detection.py` and `tokens/test_agent_spawn_integration.py` — token injection, config-dir isolation, bypass-modal auto-accept, stuck detection/recovery, log rotation, API-error heuristics
- [ ] `cd loom-daemon && cargo test` passes, including any new CLI subcommand
- [ ] loom-tools pytest suite passes after deletions (no orphaned imports; `loom_tools.models.agent_wait` and its `models/__init__.py` import remain untouched)
- [ ] `defaults/scripts/validate-toolchain.sh` passes with the console scripts removed
- [ ] Manual verification: `loom start` spawns a role successfully in a zero-pip consumer workspace (the live path being changed)
- [ ] Edge cases: spawn with no `.loom/tokens/` pool (Keychain-auth fallback preserved); stuck-session recovery path; agent-wait timeout/exit-code contract for `loom-start.sh` and `agent-destroy.sh`

### PR DESCRIPTION
**Pull request by rjwalters**
Closes #4415

Epic #4081 Phase 3, family 4 — the **session-spawn pair**, the last Python on
the manual-orchestration (`loom start` → `agent-spawn.sh`) spawn path.
`agent_spawn.py` (1165 LOC) + `agent_wait.py` (424 LOC) are ported to native
`loom-daemon agent-spawn` / `agent-wait`, and deleted along with their two
now-orphaned `common/` helpers and all five of their test files.

## Approach per seam

| Seam | Decision | Where |
|------|----------|-------|
| tmux session lifecycle | **Ported to Rust** | `agent_session/mod.rs` |
| Spawn (log rotation, pipe-pane, env, verification, bypass modal, stuck detection) | **Ported to Rust** | `agent_session/spawn.rs` |
| Wait (exit/idle/process-exit detection) | **Ported to Rust** | `agent_session/wait.rs` |
| OAuth token injection | **Reused the native selector** (was Python) | `SystemEnv::select_oauth_token` |
| `CLAUDE_CONFIG_DIR` isolation | **Reused `terminal.rs`'s `claude_config`** + new CLI | `terminal.rs`, `main.rs` |
| `agent-spawn.sh` / `agent-wait.sh` | **Repointed** stub → daemon binary | `defaults/scripts/` |
| `common/tmux_session.py`, `common/claude_config.py` | **Deleted** (no other consumers) | — |

tmux lifecycle was **not** folded into bash (which the issue permitted): the
spawn path needs pane-PID discovery, process-tree probing, and pane-content
polling, all of which bash would have re-implemented rather than avoided. The
one thing that stayed in bash is the stub's daemon-binary resolution, shared
via `lib/locate-daemon-bin.sh`.

### OAuth injection (AC 3)

`SystemEnv::select_oauth_token` calls `tokens_pool::select::select_token`
**in-process** — literally the same code `loom-daemon tokens select --export`
runs for `spawn-claude.sh` — rather than shelling out to the sibling
subcommand from inside the same binary.

One intentional behavior change: the native selector honours the
machine-level shared pool (`~/.loom/tokens`, #3938), so a consumer workspace
with no repo-local `.loom/tokens/` now gets a rotated token on the manual path
too, exactly as the daemon-dispatch path already did. With no pool at all,
nothing is injected and Claude Code falls back to the per-agent Keychain
credential under `CLAUDE_CONFIG_DIR` — unchanged.

### Config-dir isolation (AC 4)

`terminal.rs`'s private `mod claude_config` is now the **sole** implementation.
It gained the three functions that previously existed only in Python
(`validate_agent_config_dir`, `ensure_project_trusted`, `default_state_file`),
four `pub` wrappers, and a new daemon-independent CLI:

```
loom-daemon claude-config setup|cleanup|validate|trust
```

— same "no running daemon required" shape as `Clean` / `RecoverOrphans` /
`Tokens`. The spawn path consumes the wrappers directly; the CLI is the
standalone surface the AC asked for.

## Behavior preservation

All of these are unit-tested against a scripted tmux double rather than
asserted by inspection:

- `CLAUDECODE` set to an explicit empty string, never `tmux -u` (#3208).
- Config dir validated before setup, and reinitialized on corruption (#2909).
- Folder trust seeded for the **worktree path**, not the repo root (#4334).
- `GIT_WORK_TREE` / `GIT_DIR` / `LOOM_WORKTREE_PATH` pinning (#2418, #2441).
- `PYTHONPATH` prefixed with the worktree's `loom-tools/src` (#2358).
- `LOOM_SHEPHERD_TASK_ID` (#2524) and `LOOM_MAX_RETRIES` (#2516) propagation.
- Namespaced `/loom:<role>` slash command (#3345).
- Caller-supplied `CLAUDE_CODE_OAUTH_TOKEN` wins over pool selection.
- `pipe-pane` still prefers `loom_tools.log_filter` with the two `sed`
  fallbacks (zero-pip workspaces drop through cleanly).
- Bypass-permissions modal auto-accept incl. `LOOM_AUTO_ACCEPT_BYPASS=0`
  (#3348); idle-prompt detection incl. the session-age guard (#1792) and the
  two-observation confirmation.
- Logs go to **stderr**, `--json` payloads to **stdout** (unchanged, and
  load-bearing for `loom-start.sh` / `agent-destroy.sh`).

## Test coverage (AC 5)

Replacing ~115 deleted pytest cases across `test_agent_spawn.py` (72),
`test_agent_wait_sync.py` (43), `test_api_error_detection.py`,
`tokens/test_agent_spawn_integration.py`, plus `test_tmux_session.py` and
`test_claude_config.py`:

- **133** new `cargo test` cases in `agent_session` (mod/spawn/wait).
- **7** new cases in `terminal::claude_config` for the newly-added
  `validate_agent_config_dir` / `ensure_project_trusted`, including the
  write-through-symlink invariant (#2835).

The `AgentEnv` trait routes every external effect (tmux, `pgrep`, clock/sleep,
token selection, config-dir ops) so `spawn_agent` / `wait_for_agent` are
end-to-end testable with no live tmux server, no real clock, and no process
env mutation.

## Also in scope (Curator corrections)

- `tests/test_api_error_detection.py` and
  `tests/tokens/test_agent_spawn_integration.py` deleted with their module.
- `build-gate.sh:123`'s `--ignore=tests/tokens/test_agent_spawn_integration.py`
  dropped (+ the matching `build-gate.md` prose and header comment).
- `pyproject.toml` console scripts commented out with an explanatory block,
  mirroring #4416's `loom-agent-metrics` pattern.
- `validate-toolchain.sh` scrubbed in all three places — required-tools array,
  help text, **and** the console-script → module `case` map. The array is now
  empty, so its loop is length-guarded (bash 3.2 + `set -u` treats
  `"${EMPTY[@]}"` as unbound).
- `common/__init__.py` re-export removed; two stale doc references repointed
  (`advanced-hooks.md`, `lib/loom-tools.sh`'s example).
- **Out of scope, untouched:** `loom_tools.models.agent_wait` (the dataclass
  module), `models/spawn_loop_state.py`, `common/state.py`.

## Verification

- `cargo test -p loom-daemon --lib agent_session` — **133 passed, 0 failed**
- `cargo test -p loom-daemon --lib terminal` — **86 passed, 0 failed**
- `uv run pytest tests/ -q --ignore=tests/integration` in `loom-tools/` —
  **1581 passed** (no orphaned imports)
- `validate-toolchain.sh` and `--json` — exit 0, `status: ok`
- `cargo clippy --all-targets` — clean
- **Live smoke test** in a scratch repo: `agent-spawn --json` created the tmux
  session, isolated the config dir, selected a pool token, detected the
  process, and printed the JSON on stdout with logs on stderr; `--check`,
  `--list`, healthy-session idempotency, and `agent-wait --timeout 0 --json`
  all behaved as specified.

`loom start` in a zero-pip consumer workspace is the remaining manual AC — it
needs a workspace with no `loom-tools` install, which this host does not have.
The zero-pip path is what the change *enables* (the stub no longer needs
Python at all), and the smoke test above exercised the same code path.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by rjwalters** [comment]
**Independent corroboration (second Builder session)** — this issue was concurrently dispatched to several sweeps sharing the single `.loom/worktrees/issue-4415` worktree (the `--claim-owned` double-dispatch gap noted in #4415's comments). Rather than open a competing PR, I verified this one. Notes for the Judge:

**Provenance is clean.** The branch is a single commit (`d6cceeb9`) on top of `main` — no competing commit was force-pushed away and no work is split across sessions. `git reflog` in the shared worktree shows the earlier partial WIP was reset before this commit was authored, not merged into it.

**Test corroboration.** Running the Python suite independently via `PYTHONPATH=loom-tools/src` (rather than `uv run`) gives **1580 passed, 1 failed** — the one failure is `test_logging.py::test_log_output_visible_non_interactively`, which spawns a subprocess with `env={"PATH": "/usr/bin:/bin"}` and so needs an *installed* `loom_tools`. That is an artifact of my invocation, not of this PR: the file is untouched here (last modified by #2820), and it passes under `uv run`, which is how `build-gate.sh` invokes pytest — consistent with the PR body's 1581. No orphaned imports from the deletions.

**AC spot-checks against the diff** (all confirmed):

- OAuth injection — `SystemEnv::select_oauth_token` → `crate::tokens_pool::select::select_token(repo_root, None)` (`agent_session/mod.rs:450`); caller-supplied `CLAUDE_CODE_OAUTH_TOKEN` still wins (`spawn.rs:707`).
- Config-dir isolation reuses `terminal.rs`'s `claude_config` (widened, not reimplemented) behind the new `loom-daemon claude-config setup|cleanup|validate|trust`.
- `find_repo_root` (`mod.rs:309`) does the **gitlink walk** (`gitdir:` → ascend) plus the `.loom/`-must-exist requirement, so a call from inside `.loom/worktrees/issue-N` resolves the *main* checkout — this is the trap `worktree_ops::repo::find_repo_root` would have fallen into (agent logs/config written into the worktree).
- Exit-code contract preserved: `wait.rs` `exit_code()` maps completed/timeout/other → 0/1/2, with a dedicated test.
- All three `validate-toolchain.sh` sites scrubbed (array + help text + module `case` map), with the empty-array loop length-guarded for bash 3.2 + `set -u`.
- `pyproject.toml` uses the comment-out-with-rationale pattern from #4416, not silent deletion.
- `build-gate.sh` `--ignore=tests/tokens/test_agent_spawn_integration.py` dropped along with `build-gate.md`'s prose.
- `loom_tools.models.agent_wait` (the dataclass module) is untouched, as the issue's disambiguation note requires.

**Test-count sanity:** `grep -c '#\[test\]'` in `agent_session/` gives 23 (`mod.rs`) + 78 (`spawn.rs`) + 32 (`wait.rs`) = **133**, matching the claim.

I did not reproduce `cargo test` locally — the shared `target/` build lock was saturated (host load average 57 from concurrent worktree builds), so CI's `Rust Unit Tests` is the authoritative signal here.

**Comment by rjwalters** [comment]
**⚠️ The two red Rust checks on this PR are inherited from `main`, not caused by this diff.** Filed as #4474.

`Rust Unit Tests` and `Rust Linting & Build Check` fail with:

```
error[E0063]: missing field `death_class` in initializer of `types::Event`
    --> loom-daemon/src/safehouse.rs:2717:21
    --> loom-daemon/src/safehouse.rs:2773:21
error: could not compile `loom-daemon` (lib test) due to 2 previous errors
```

`loom-daemon/src/safehouse.rs` is **not** in this PR's diff (`git show --name-only d6cceeb9 | grep safehouse` → no match). The breakage is a semantic merge conflict already on `main`:

| Commit | Subject | Rust CI |
|---|---|---|
| `f6583a7c` | `feat(safehouse): emit completion envelopes for merged sweeps (#4426)` | green |
| `1085e40b` | `fix(daemon): classify claude-wrapper pre-flight deaths…` (#4386) | **red** |

`#4426` added the two `Event::SweepExited { .. }` test initializers in `safehouse.rs`; `#4386` added the `death_class` field to that variant (`types.rs:1586`) and updated every initializer *on its own branch*, which was cut before `#4426` merged. Both were green; their merge is not. Every PR opened since `1085e40b` inherits it, since CI builds the merge with `main`.

Per the Builder role's "do not fix pre-existing issues in other files — file a separate issue" rule, I have **not** folded the two-line fix (`death_class: None,` at both sites) into this PR. Once #4474 lands on `main`, re-running these two checks here should clear them with no change to this branch.

**Judge note:** the remaining green checks (`Shellcheck`, `Installer Integration Tests`, `CLAUDE.md Line Budget`, `Detect Changes`) all passed, and `Installer Integration Tests` is the one that exercises this PR's bash-side cutover (`agent-spawn.sh` / `agent-wait.sh` / `validate-toolchain.sh`). The Rust side was verified locally by the authoring session (133 `agent_session` + 86 `terminal` cases green) against the pre-`1085e40b` base, which is exactly why the local run did not reproduce this.

**Comment by rjwalters** [comment]
✅ **Approved!**

Reviewed as Judge. This is an unusually disciplined Python→Rust port — the parity claims in the description hold up under line-by-line comparison against the deleted originals, and the test coverage genuinely replaces what was removed rather than just outnumbering it.

### Stale-red CI cleared

The earlier red (`Rust Unit Tests`, `Rust Linting & Build Check`) was **inherited from a broken main**: `error[E0063]: missing field death_class` at `safehouse.rs:2717`/`2773`, a file this PR does not touch (fixed on main at `fc4578a2`). I updated the branch (`56e27299`, merge of main) and all checks are now green — **no failure was attributable to this PR**:

```
Rust Unit Tests            success      Rust Linting & Build Check  success
Shellcheck                 success      Installer Integration Tests success
Codex Adapter Smoke        success      CLAUDE.md Line Budget       success
```
`mergeable: true`, `mergeable_state: clean`.

### (a) Behavioral parity vs. the Python originals

Compared against `git show a4322f87:` for both deleted modules:

- **`agent_wait.py` → `wait.rs`** — completion-detection order is identical (session-destroyed → `/exit` in log → shell-PID refetch → claude-process → idle-prompt → timeout), as are all four `reason` strings, the `WaitResult.to_dict()` shape (including the `timeout` key that duplicates `elapsed` to match the original bash), and the `0/1/2` exit-code map. The `timeout == 0` non-blocking branch keeps the session-age guard (#1792) rather than the elapsed-time guard, and the blocking branch keeps `IDLE_PROMPT_CONFIRM_COUNT = 2` with the reset-on-activity behavior.
- **`agent_spawn.py` → `spawn.rs`** — `build_claude_command` reproduces the env-prefix **ordering** byte-for-byte (token → `PYTHONPATH` → `LOOM_WORKTREE_PATH` → `LOOM_MAX_RETRIES` → `LOOM_SHEPHERD_TASK_ID` → `LOOM_TERMINAL_ID`/`LOOM_WORKSPACE`/`CLAUDE_CONFIG_DIR`/`TMPDIR` → wrapper), including the detail that the wrapper-less fallback carries **only** the token prefix. `sh_escape` matches Python's `'"'"'` scheme and is tested directly. Extracting this as a pure function with the "an env-prefix ordering slip silently changes which token, config dir, or worktree the agent runs under" comment is the right call — that string is the whole contract.
- **`claude_config.py` → `terminal.rs`** — `ensure_project_trusted` preserves the `LOOM_AUTO_TRUST` gate, the idempotent no-op-when-already-trusted path (no rewrite), the entry-merge semantics, and the #2835 write-through-symlink invariant. The `fs::canonicalize` vs. Python's non-strict `Path.resolve()` difference is behaviorally equivalent: canonicalize fails on a dangling symlink, so it falls through to unlink-and-recreate exactly as the Python did.

Spot-verified the specific regressions the description claims to preserve: `CLAUDECODE` set to explicit empty string with a test asserting `-u` is *never* used (#3208), trust seeded for the **worktree** path not the repo root (#4334), `GIT_WORK_TREE`/`GIT_DIR` set only when `worktree && working_dir != repo_root`, and the `--min-idle-elapsed` deprecated argparse alias carried over as a clap `alias`. That last one is the kind of thing ports usually drop.

**The one intentional behavior change is correctly disclosed**: dropping the repo-local `tokens_dir.is_dir()` pre-check means `select_oauth_token` now honours the machine-level shared pool (`~/.loom/tokens`, #3938) on the manual path too. This converges the manual path with daemon-dispatch rather than diverging it, and the no-pool case still returns `None` → Keychain fallback under `CLAUDE_CONFIG_DIR`, unchanged.

### (b) Test coverage replacing the deleted suites

The deleted pytest files are replaced by targeted equivalents, not just bulk count. Notably `test_api_error_detection.py` → the `check_log_for_api_errors` block in `spawn.rs` (explicitly labelled `replaces test_api_error_detection.py`), which iterates `API_ERROR_PATTERNS` so a pattern added later cannot silently go untested. The `AgentEnv` trait routing every external effect (tmux, `pgrep`, clock, token selection, config-dir ops) is what makes `spawn_agent`/`wait_for_agent` testable end-to-end with no live tmux and no real clock — the right seam.

### (c) Import graph — clean (this family's known trap)

Grepped the whole repo for `loom_tools.agent_spawn`, `loom_tools.agent_wait`, `loom_tools.common.claude_config`, `loom_tools.common.tmux_session`, and both console-script names. Every surviving hit is a comment or doc reference. The only live code matches are the deliberately out-of-scope `loom_tools.models.agent_wait` dataclass module (still imported by `models/__init__.py`, `test_agent_wait.py`, `test_validate_phase.py`) and `paths.claude_config_base_dir` — a same-named path helper, not the deleted module. `common/__init__.py`'s re-export was removed. No orphaned importers.

The `validate-toolchain.sh` scrub caught the trap I'd have flagged: `OPTIONAL_COMMANDS=()` is now empty, and the loop is length-guarded because bash 3.2 + `set -u` treats `"${EMPTY[@]}"` as unbound. Also correctly scrubbed in all three places (array, help text, module `case` map) and the `build-gate.sh:123` `--ignore` dropped with its matching prose.

### (d) Local verification

| Check | Result |
|---|---|
| `cargo test --lib agent_session` | **133 passed, 0 failed** (matches claim) |
| `cargo test --workspace` (lib) | **2116 passed, 0 failed** |
| `cargo clippy --all-targets --all-features -- -D warnings` | clean |
| `cargo fmt --all -- --check` | clean |
| `uv run pytest tests/ -q --ignore=tests/integration` | **1581 passed** (matches claim; no orphaned imports) |
| `agent-spawn` / `agent-wait` / `claude-config --help` | exit 0, help renders |

`tests/integration_basic.rs` fails locally (9 cases, `Daemon failed to create socket within 5s`) — **environmental, not this PR**: the production daemon (pid 35554) holds the socket on this host, and these same tests pass in CI on a clean runner and on main's tip. This is exactly the local-gate-vs-CI split `build-gate.md` documents.

### Non-blocking notes (no action required)

1. `validate-toolchain.sh:141-152` — tier 3 of `command_exists` is now unreachable (`case "$cmd" in *) return 1 ;;` means `local module_name` and the `python3 -c "import $module_name"` block can never execute). The comment states this is deliberately kept as an extension point, which is a defensible call, so I'm not asking for a change — just flagging that a future reader may mistake it for a bug.
2. `wait.rs:317` uses `env.sleep(opts.poll_interval.max(1))` where Python used a bare `time.sleep(poll_interval)`, so `--poll-interval 0` now sleeps 1s instead of hot-spinning. A strict improvement, and unreachable in the `timeout == 0` path which returns on the first pass.
3. `.loom/docs/advanced-hooks.md:165` still carries the old `loom_tools.common.claude_config.resolve_projects_dir()` reference — but that's the stale *installed* copy, not a source file; `defaults/docs/advanced-hooks.md` is correctly repointed in this PR. `resync-installed.sh` handles it.

Correctly uses `Closes #4415` (the child issue), leaving epic #4081 open for the remaining phases.
