### ISSUE TITLE
/sweep should auto-stack same-file/dependent issues by default instead of serializing on merge

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/loom#3759]
## Curator enhancement — v1 scope for this PR (2026-07-22)

This is a large orchestration-redesign proposal (auto-elect stacking for same-file/dependent issues, replacing serialize-on-merge). Curator's job here is to pin down a **realistic, single-PR-landable v1 slice**, not to spec the whole thing. **Only the sections below are authoritative scope; the original request (preserved at the bottom) is context, not a spec to implement in full.**

### Honesty check on sizing

Even the trimmed slice below touches five places inside one large prose skill file (`defaults/.claude/commands/loom/sweep.md`): the flags/validation table, the Stage 0 candidate survey + dry-run output, the wave-partition ordering pass, the Builder-phase stacked-dependency gate, and the Stage -1 daemon-dispatch loop — plus a new doc-shape test file. That is meaty for a markdown-only PR. If it doesn't fit in one reviewable PR, take the **v1a fallback** below (detection-only advisory + a documented manual recipe) rather than force the full auto-election through.

### What already exists (do not re-build)

As of #3729 (v1, merged) and #3747 v2 item 1 / #3752 (merged), the *mechanics* of stacking are fully shipped:
- `--depends-on <parent>` on `/loom:sweep` / `mcp__loom__dispatch_sweep` (`depends_on`): a **single-issue, daemon-dispatch-only** flag that makes one Builder branch off `feature/issue-<parent>` via `worktree.sh --base` and open its PR with `--base feature/issue-<parent>` (sweep.md:123-127, gated path at sweep.md:1235-1238).
- `defaults/scripts/worktree.sh --base <branch>` (worktree.sh:439,456,639-663,833-859) — resolves and branches off an arbitrary base.
- Automatic post-merge reconciliation (`merge-pr.sh`'s `_auto_reconcile_stacked_children`, #3752, merged) — no manual `reconcile-stack.sh` step needed anymore for the safe case.

**What is missing, and the sole gap this issue should close**: `/sweep` never **auto-elects** to use any of the above. Today, when a multi-issue `/sweep` wave contains two candidates where one's body says "Depends on #other-candidate-in-this-set", nothing detects that — both get built off the same pre-wave `main` snapshot in parallel (or fully serialized across waves), relying on the *reactive* #3647 intra-wave overlap-and-revalidate gate (sweep.md:1360-1379) if they happen to touch the same files. That reactive gate is a safety net for *accidental* collisions, not a mechanism for *pipelining a declared dependency* — it still rebuilds/re-judges the second PR after the first merges rather than letting it build concurrently on the first PR's branch.

### v1 scope (land in this PR)

1. **New opt-in flag `--auto-stack` (default off).** Applies only to Mode A/B (issue-set); Mode C (PR-set) is unaffected — it has no Builder phase to stack. Absent the flag: **byte-for-byte unchanged** behavior (today's parallel/serialize-on-merge default). Document it alongside the existing `--depends-on` entry (sweep.md:123-127) in "Optional flags" / "Validation rules".
2. **Detection — authoritative body-text signal only, restricted to same-candidate-set edges.** During the existing per-candidate survey (Stage 0 dry-run gate, sweep.md:828-836; the live-path equivalent at the top of "Wave Lifecycle", sweep.md:1067+), add `body` to the already-issued `gh issue view N --json ...` read (no new API call) and grep it for `(Depends on|Requires) #[0-9]+` — **reuse the exact regex vocabulary already established in `defaults/roles/guide.md:486`** (`(Blocked by|Depends on|Requires|\- \[.\]) #[0-9]+`), restricted to `Depends on` / `Requires` only (deliberately **excluding** `Blocked by` — that phrase already drives the distinct `loom:blocked`-unblock machinery in `guide.md`/`champion-reference.md` and should not be repurposed here). A match on `#A` becomes a stacking edge **only when `#A` is also present in this sweep invocation's own deduplicated candidate list** — a `Depends on #A` naming an issue outside the set is left completely untouched (flows through existing `loom:blocked` handling, unaffected by this issue).
3. **Linear edges only; cycle guard, no diamond support.** A single candidate may declare at most one in-set parent (mirrors #3729's `Option<u32>` design — do not build a `Vec`). If a body matches multiple in-set `#A` references, take the first and log a warning that only single-parent edges are honored. If detected edges form a cycle within the candidate set, drop every edge in the cycle (log a warning) and fall back to default behavior for those issues — never silently pick a direction.
4. **Operator confirmation — reuse the existing gate, do not invent a new one.** When `--auto-stack` finds at least one edge, print a "Detected stacking pairs" block as part of the same candidate-set display Mode B / `--dry-run` already show before awaiting confirmation (sweep.md:845-869 dry-run output spec), e.g. `#125 "Fix Y" — Depends on #124 (in this sweep's candidate set) → will stack on #124's branch`. **Mode A (explicit numeric list, today's no-prompt fast path) gains a confirmation prompt only when `--auto-stack` actually found ≥1 edge** — a zero-edge `--auto-stack` run on Mode A stays prompt-free. Declining exits cleanly, matching every other gate in this skill.
5. **Wave ordering.** After edges resolve, order candidates so every parent lands in a wave at or before its child's wave (a topological pass restricted to the linear-chain shape above — no general DAG solver needed). A parent/child pair may land in the *same* wave: the child's Builder still branches off the parent's branch via `--base`, not off the shared pre-wave `main` snapshot its other wave-mates use.
6. **Dispatch — generalize existing single-value `DEPENDS_ON` into a per-issue lookup, mechanics unchanged.**
   - **Subagent path** (Builder phase, sweep.md:1213-1238): today's gate fires only when the single global `DEPENDS_ON` (from `--depends-on N`) is set. Generalize to `DEPENDS_ON[N]`, populated either by the existing single-issue `--depends-on` flag (unchanged) or by an auto-stack-detected edge for candidate `N`. The underlying `worktree.sh N --base feature/issue-<parent>` / `gh pr create --base feature/issue-<parent>` mechanics are **not** touched — only how the per-issue value is sourced.
   - **Daemon path** (Stage -1 dispatch loop, sweep.md:724-736): today every candidate dispatches as `mcp__loom__dispatch_sweep(kind={"Issue": N})` with no `depends_on` forwarded at all. When auto-stack detected an edge for `N`, forward it: `mcp__loom__dispatch_sweep(kind={"Issue": N}, depends_on=<parent>)`. The daemon and MCP tool schema already accept this field (#3729/#3742) — this is purely "start populating a parameter that already exists," no daemon-side code changes.
7. **Reconciliation — reuse, do not touch.** No changes to `merge-pr.sh`; the already-shipped automatic post-parent-merge reconciliation (#3747 v2 item 1 / #3752) handles the squash-merge rebase-and-retarget for any edge this feature creates, exactly as it does for a manually-dispatched `--depends-on` chain today.

### Explicitly OUT of scope for this PR (do not attempt)

- **File-overlap-heuristic auto-detection** (inferring a dependency from curated `## Affected Files` overlap, or from any changed-path prediction). #3729 explicitly rejected file-path overlap as a topology signal — it is real for the *reactive* wave-7 collision-and-serialize backstop (already implemented, stays as the fallback for anything this feature doesn't stack), but too weak to *decide* which issue should branch off which. v1 uses **only** the authoritative same-set `Depends on #A` / `Requires #A` body signal.
- **Diamonds / multi-parent stacks** — structurally unrepresentable by design (item 3 above), consistent with #3729/#3747.
- **Cross-sweep coordination.** Two independently-running `/sweep` invocations discovering and stacking each other's candidates across process boundaries is **#3768's scope** (peer-`/sweep` detection + shared-run-state isolation), not this issue's. This issue only ever stacks within **one** sweep invocation's own resolved candidate set.
- **`Part of #A` / `Blocked by #A` timeline cross-reference detection** (the #3359/#3677 union probe). v1 sticks to the simpler, already-precedented `guide.md` body-grep convention.
- **Auto-detach, rebase-on-parent-amend, merge-ordering guard** — all remain #3747's own deferred items; nothing here touches them.
- **Mode C (PR-set mode).** No Builder phase exists to stack.

### v1a fallback (if v1 above still doesn't fit in one PR)

Drop items 1, 3, 5, 6 (the actual auto-election + dispatch wiring) and land only:
- **A documented manual-stacking recipe**: a new sweep.md subsection walking an operator through composing several separate `--depends-on`-flagged dispatches to hand-stack a chain that spans one logical batch of work (today's docs only show a single-issue `--depends-on` example — extend it to the multi-issue-batch case explicitly).
- **A detection-only advisory** (item 2's detection pass, with no wave-ordering or dispatch changes): when same-candidate-set `Depends on #A` edges are found, print a **non-blocking** note in the candidate-set / dry-run output — e.g. "`#125` declares 'Depends on #124', also in this candidate set — these will build independently and reconcile via the #3647 in-wave overlap guard / serialize-on-merge; re-run with per-issue `--depends-on` flags to stack them instead." Nothing about dispatch or ordering changes; this is pure information.

State plainly in the PR description which slice (v1 or v1a) was landed, and if v1a, open a fast-follow issue for full auto-election — the same decomposition pattern #3747 used against #3729.

### Sequencing note (not part of this issue's own scope)

Per the operator's stated batch ordering, this issue is the top of a three-issue chain (**#3770 → #3768 → #3759**, this issue last). #3768 (peer-`/sweep` detection + per-run checkpoint/baseline isolation) is worth landing first since it also touches sweep.md's Stage -1 / wave-setup sections this issue edits — landing #3768 first reduces merge-conflict risk for whichever of the two lands second. This is scheduling advice for whoever dispatches the batch, not an enforced dependency (v1 above deliberately does not implement cross-issue body-text dependency detection outside a single sweep's own candidate set, so this note is not "dogfooded" by the feature it describes).

### Acceptance criteria

- [ ] `--auto-stack` flag documented and validated in sweep.md's "Optional flags" / "Validation rules" (alongside `--depends-on`, sweep.md:123-127); absent → byte-for-byte unchanged behavior; applies to Modes A/B only, no-op note for Mode C.
- [ ] Stage 0 candidate survey (Modes A/B) fetches `body` alongside existing fields and detects same-candidate-set `Depends on #A` / `Requires #A` edges using the `guide.md:486`-derived regex, restricted to `Depends on`/`Requires` (not `Blocked by`).
- [ ] Detected edges are single-parent (first-match-wins with a logged warning on multiple matches) and cycle-checked (cyclic edges dropped with a logged warning, never silently resolved).
- [ ] Candidate-set display / `--dry-run` output shows a "Detected stacking pairs" block when `--auto-stack` finds ≥1 edge; Mode A only prompts for confirmation when an edge was actually found (zero-edge Mode A stays prompt-free).
- [ ] Wave partition orders every parent's wave at-or-before its child's wave; a parent/child pair may share a wave.
- [ ] Builder-phase stacked-dependency gate (sweep.md:1213-1238) is generalized from a single global `DEPENDS_ON` to a per-issue `DEPENDS_ON[N]` lookup, sourced from either the existing single-issue `--depends-on` flag or an auto-stack-detected edge; `worktree.sh --base` / `gh pr create --base` mechanics are unchanged.
- [ ] Daemon-dispatch loop (sweep.md:724-736) forwards `depends_on=<parent>` on `mcp__loom__dispatch_sweep` for any candidate with a detected edge; unaffected candidates dispatch exactly as today (no `depends_on` param).
- [ ] No changes to `merge-pr.sh`, `reconcile-stack.sh`, `worktree.sh`, or any daemon/MCP Rust or TypeScript source in this PR — v1 is sweep.md prose plus one new doc-shape test file only.
- [ ] New doc-shape test file (modeled on `defaults/scripts/tests/test-sweep-pr-mode.sh`'s grep-assertion pattern) verifies: the `--auto-stack` flag is documented, the detection regex/behavior is described, the confirmation-gate language is present, and the "same-candidate-set only" restriction is explicitly stated (guards against a future edit silently broadening detection to arbitrary external issues).
- [ ] If v1a is taken instead, the PR body says so explicitly and a fast-follow issue is opened for the full auto-election slice.

### Affected Files

- `defaults/.claude/commands/loom/sweep.md` — `--auto-stack` flag + validation (near lines 123-127); Stage 0 detection pass (Modes A/B survey, lines 828-836 and dry-run output spec 845-869); wave-partition ordering (Wave Lifecycle intro, line 1067+); Builder-phase per-issue `DEPENDS_ON[N]` generalization (lines 1213-1238); daemon-dispatch loop forwarding `depends_on` (lines 724-736).
- `defaults/scripts/tests/test-sweep-pr-mode.sh` — existing doc-shape test pattern to model the new test file on (do not modify this file itself unless trivially necessary).
- `defaults/scripts/tests/test-sweep-auto-stack.sh` — **new file**, doc-shape assertions per the AC above.
- `defaults/roles/guide.md` — read-only reference; reuse (do not modify) the existing `(Blocked by|Depends on|Requires|\- \[.\]) #[0-9]+` regex convention at line 486.

### Test Plan

- [ ] Run the new `defaults/scripts/tests/test-sweep-auto-stack.sh` (and the existing `test-sweep-pr-mode.sh`, unaffected) — both pass.
- [ ] Manual/integration verification (sweep.md is prose, no compiled test harness): construct two scratch issues where the second's body contains `Depends on #<first>`, run `/loom:sweep <first> <second> --auto-stack --dry-run` and confirm the dry-run plan shows the detected edge and the correct wave ordering; repeat without `--dry-run` on a real (or simulated) pair and confirm the child's worktree/PR bases off the parent's branch, not `main`.
- [ ] Confirm `/loom:sweep <first> <second>` (no `--auto-stack`) is byte-for-byte unchanged — regression check on the default path.
- [ ] Confirm `/loom:sweep <first> <second> --auto-stack` with **no** detected edges behaves identically to the flag being absent (no spurious prompts, no wave reordering).
- [ ] Confirm a candidate whose body says `Depends on #<issue-not-in-this-set>` is left untouched by this feature (still routes through existing `loom:blocked` handling only).

---

## Original request (context only — not authoritative scope; see v1 above)

Surfaced live during a `/loom:sweep` run (2026-07-22). Three issues (#3755, #3756, #3757) all rewrite the same file (`defaults/hooks/guard-destructive.sh`), so they cannot parallelize as independent Builders — they'd collide. The operator's instinct was "sweep these four in parallel," and the honest answer was "three of them can't." The fallback was to serialize the trio (build→merge→build→merge→build→merge), which stacks each issue's full latency behind the prior's review+merge.

The operator asked: use stacked PRs to accelerate the serial chain, and ideally make this a default Loom behavior.

The primitives already exist as of this session:
- `worktree.sh --base <branch>` (#3742) — branch a child off a parent's PR branch.
- `reconcile-stack.sh` + auto-reconciliation on parent merge in `merge-pr.sh` (#3747 item 1 / #3752) — retarget/rebase children onto `main` when the parent squash-merges.
- Operator-declared `--depends-on` dispatch param on the daemon path (#3729/#3742).

What was missing (and is now this issue's v1 scope, above) is the in-session `/sweep` orchestration that automatically recognizes when candidate issues in a wave contend on the same file (or declare a dependency) and stacks their Builders — narrowed by curation to the declared-dependency case only; the file-overlap case is explicitly deferred (see "Explicitly OUT of scope" above).

### Relation to existing work

This is the in-session-`/sweep` counterpart to the daemon-path stacked-PR mode (#3729 / #3747). #3747's v2 epic covers the daemon/merge-ordering mechanics; this issue is specifically about `/sweep` auto-electing to stack rather than requiring the operator to hand-drive `--base`.
