### ISSUE TITLE
TestStaleBranchDetection still failing: mock missing warnings attribute

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/loom#2379]
## Problem

`TestStaleBranchDetection::test_warns_when_stale_branch_exists` is still failing after the `label_cache` mock fix in PR #2376. The `label_cache` fix resolved the first error but exposed a second one: the mock `ShepherdContext` is missing the `warnings` attribute.

```
loom-tools/src/loom_tools/shepherd/context.py:303: in _check_stale_branch
    self.warnings.append(msg)
AttributeError: Mock object has no attribute 'warnings'
```

This is the same pattern as #2375 — a mock `ctx` that doesn't include all the attributes the real `ShepherdContext` uses.

## Reproduction

```bash
PYTHONPATH=loom-tools/src:$PYTHONPATH python3 -m pytest loom-tools/tests/shepherd/test_phases.py -k "TestStaleBranchDetection" -v
```

Result: 1 failed, 3 passed

## Fix

Add `warnings` (as a list) to the mock `ctx` in `TestStaleBranchDetection` setup, similar to how `label_cache` was added in PR #2376.

## Affected files

- `loom-tools/tests/shepherd/test_phases.py` — `TestStaleBranchDetection` class

## Related

- #2375 — Original 13 failing tests (closed by PR #2376, but this test still fails)
- PR #2376 — Added `label_cache` to mocks, unmasking this second missing attribute

**Comment by rjwalters** [comment]
This issue was already resolved by PR #2376 (commit 16210a6), which added both `label_cache` and `warnings` mocks to `test_phases.py`.

All 4 `TestStaleBranchDetection` tests pass, and the full `test_phases.py` suite (564 tests) passes cleanly.

The `mock_context` fixture at line 51 already includes `ctx.warnings = []` (line 60). No additional changes are needed.

Closing as already fixed.
